### ISSUE TITLE
Push version numbers in files that have not changed

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#1]
Should we change the revision metadata in schema files that have not changed:
iati-organisations-schema.xsd has not changed but the iati-common.xsd it relies on has.

Similarly the registry-record schema has not changed.

**Comment by davidmegginson** [comment]
I agree.  I'll tag the 1.02beta release, then make this change in preparation for the final release.

**Comment by caprenter** [comment]
I've made the change to version numbers as discussed. I think is ready to roll
