### ISSUE TITLE
Add a Schema Version Attribute to the root element

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#10]
Details: http://wiki.iatistandard.org/standard/revision/1.03/changes_specification?&#add_a_schema_version_attribute_to_the_root_element

**Comment by caprenter** [comment]
see: https://github.com/davidmegginson/iati-schemas/commit/cbdf0a98f92342b2658f5e837118f45e3a6f438a

**Comment by davidmegginson** [comment]
I think this is the right commit: https://github.com/davidmegginson/iati-schemas/commit/3b4bac947da6c58a1699d9866dc07fc931c43911

Thanks for adding the attribute.  Verified, and closing the issue.
