### ISSUE TITLE
2.01 - iati-activity/@last-updated-datetime

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Schemas#102]
Do we need this to be mandatory.

I think so.

**Comment by Bjwebb** [comment]
In order to have it be usefully mandatory, we also need to ensure it gets used properly - ie. that it is updated each time the data is updated, and is not in the future (see http://data.tickets.iatistandard.org/ticket/107 for the current data issue).

**Comment by Bjwebb** [comment]
I think we discussed this on a call, and agreed that it is not useful for us to make this mandatory at the moment, as we'd need our own mechanism to check it anyway. Therefore, I'm closing this issue.
