### ISSUE TITLE
2.01 - iati-activity/@xml:lang

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Schemas#103]
This will now become standard (along with current definition) for all narrative elements. But here it refers to the default language to be used throughout the activity. Should it therefore be called default-language?

**Comment by Bjwebb** [comment]
No, I don't think so. Whilst I can see the appeal of `default-language` for consistency with `default-currency` etc., I think our current use of `@xml:lang` is correct, as that's how XML standards people use it. `@xml:lang` is the language of an XML element (unless overridden) so when applied to `iati-activity` it acts as the default language.

To make it clearer what `@xml:lang` means on different elements, we can have different descriptions depending on whether it's on iati-activity or narrative. I've already added this to the schema:  https://github.com/IATI/IATI-Schemas/commit/ddeea022b95bbee80f22b3a38253091d1a0810d3
