### ISSUE TITLE
OrganisationType - missing from provider and receiver org

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#104]
The `OrganisationType` is not an attribute for `provider-org` and `receiver-org` , yet it is for other organisation type elements.  

Is there a design reason for this @bill-anderson ?

**Comment by bill-anderson** [comment]
The thinking was that participating-org describes all organisations involved. provider-org is describing a bank account (cf note on recipient and receiver)

I'm happy for this to be reconsidered in 1.05 consultation if anyone feels passionate about it.

**Comment by stevieflow** [comment]
moving to post 1.04 - most probably create a forum post to discuss

**Comment by Bjwebb** [comment]
Bumping this to 2.02 as 1.05 is codelist only, and it's too late for 2.01.

@stevieflow Could you create a forum post?

**Comment by stevieflow** [comment]
Done: http://support.iatistandard.org/entries/81683876-provider-receiver-og-adding-type
