### ISSUE TITLE
How should publishers report their own sector codelist?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#105]

**Comment by bill-anderson** [comment]
1. sector/@vocabulary-url (lots of repetition)
2. iati-activities/sector-vocabulary-url (but then not available in activity blobs)
3. In a new reference section in the organisation file

?????

**Comment by Bjwebb** [comment]
I like `sector/@vocabulary-url` because it would be available in activity blobs. There's also the option of having `iati-activity/@sector-vocabulary-url`. I think `sector-vocabulary-url` is a bit problematic, because it doesn't make it clear that it applies only to RO (99) sectors.

A problem I can see with `sector/@vocabulary-url`, besides the repetition, is that people might think they can have multiple RO vocabularies with different urls. We'd should either make it clear this isn't possible, or explicitly permit it.

This change is currently in a 2.01 milestone, mostly because it's the nearest one. Is this is a change we are considering for 2.01, or should it go into one of the decimal processes?

**Comment by Bjwebb** [comment]
@bill-anderson This change is currently in a 2.01 milestone, mostly because it's the nearest one. Is this is a change we are considering for 2.01, or should it go into one of the decimal processes?

**Comment by bill-anderson** [comment]
Overlooked 
I think we can add it in as it won't disrupt anything

**Comment by Bjwebb** [comment]
After discussing this on a call, we decided it was too late in the process to add this, and to put it into 2.02.

**Comment by akmiller01** [comment]
This seems to have made it into the standard as of 2.03, so I think this is safe to close https://github.com/IATI/IATI-Schemas/blob/version-2.03/iati-activities-schema.xsd#L607
