### ISSUE TITLE
documentation on how to follow schema branches

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#107]
I don't think we have any guidance about how to follow schema version branches.

We should eb saying something along the lines of official releases are tagged as releases, but that bug fixes (?) may be added after that - people can download tagged releases via the iatistandard site (? or follow the schema on github?)

**Comment by Bjwebb** [comment]
The closest thing to this atm is http://dev.iatistandard.org/developer/ssot/#finding-a-specific-version-of-the-ssot

**Comment by stevieflow** [comment]
Does this belong in this repository, or better in Guidance?

**Comment by Bjwebb** [comment]
I think this is aimed at a technical audience, so it might go in the README in this repository, or it might go in the Developer Documentation. I'm not sure if it would go in the Guidance repository.

**Comment by Bjwebb** [comment]
@caprenter Does http://iatistandard.org/201/developer/ssot/#finding-a-specific-version-of-the-ssot cover this? What extra information are you looking for?

**Comment by caprenter** [comment]
I think  the information you have pointed to is enough - thanks.
