### ISSUE TITLE
Order of location sub-elements

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#108]
Is there a reason for the order to be as such:

location-reach
location-id
location-type
name
description
activity-description
administrative
point
exactness
location-class
feature-designation
coordinates
gazetteer-entry

If location-type is deprecated - would it make sense to have this at the footer of the list too?

It's also unclear as to the status of name/description: https://github.com/IATI/IATI-Extra-Documentation/issues/125

**Comment by bill-anderson** [comment]
location-id
name
description
activity-description
administrative
point
exactness
location-reach
location-class
feature-designation

coordinates
gazetteer-entry
location-type

**Comment by stevieflow** [comment]
Updated: https://github.com/IATI/IATI-Extra-Documentation/commit/fec41af21e1961a3d6bea44f412226d373b4ecfe

Over to @Bjwebb for schema order change
