### ISSUE TITLE
Implement 2.01 "Tightening up on version"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#109]
http://support.iatistandard.org/entries/57866638-Tightening-up-on-version
http://support.iatistandard.org/entries/57972186-Version-2-01-Iteration-1-8-Miscellaneous/
http://support.iatistandard.org/entries/77311697-Version-2-01-Iteration-2-8-Miscellaneous

Previous discussion on GitHub: https://github.com/IATI/IATI-Schemas/issues/100
- [x] iati-activities/@version is MANDATORY
- ~~[x] iati-activity/@version is MANDATORY~~
- ~~[ ] All @version attributes in a given file MUST have the same value~~
- [x] The value of @version MUST be on the (new to 2.01) version codelist https://github.com/IATI/IATI-Schemas/issues/101
- [x] Should the same rules apply to the organisation standard?

**Comment by Bjwebb** [comment]
Note that the type of the `@version` attribute is now `xsd:string` instead of `xsd:decimal` because it is not meaningfully a decimal, since the codelist must be matched exactly. (e.g. 2.01 and 2.010 are not equivalent).

**Comment by caprenter** [comment]
We need to work out how to communicate:
All @version attributes in a given file MUST have the same value
to publishers.

We can't enforce via the schema or rulesets - so can only really give guidance - should this be in the schema or elsewhere?

**Comment by Bjwebb** [comment]
Following http://support.iatistandard.org/entries/57866638#view-post-26238806 we no longer need to enforce that all `@version` attributes in a file are the same, as there will be only `iati-activities/@version`.

We also now need to:
- [x] Remove `iati-activity/@version` and `iati-organisation/@version` from the schema

**Comment by caprenter** [comment]
Just seeking clarification. Are we actually removing the @version attribute from these elements, or just removing the requirement that they are mandatory (and leaving the attribute in place, but optional)?

**Comment by bill-anderson** [comment]
Not sure what value an optional attribute is to users. I favour dropping

**Comment by Bjwebb** [comment]
I'd agree, I think an optional attribute is actively unhelpful. It leads to potential confusion if people aren't consistent with their versions. Having @version on iati-activities only means we have a "single source of truth" for the version number of a file.
