### ISSUE TITLE
Use decimal instead of integer for currency values

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#11]
Details: http://wiki.iatistandard.org/standard/revision/1.03/changes_specification?&#currency_values_as_decimal

**Comment by caprenter** [comment]
see commit: https://github.com/davidmegginson/iati-schemas/commit/cbdf0a98f92342b2658f5e837118f45e3a6f438a

**Comment by davidmegginson** [comment]
David: the change is checked into the pre-version1.03 branch, along with verification tests.

Can you please confirm and close the issue (or reassign to me, if there are any problems)?

**Comment by caprenter** [comment]
Looks good to me
