### ISSUE TITLE
document-link/category

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#111]
In line with https://github.com/IATI/IATI-Extra-Documentation/issues/147 it may be worth adding to the schema description that multiple category elements are permissible ?

**Comment by Bjwebb** [comment]
This is a change that should be made in 2.01 if we want to make it.

We've not yet looked into enforcing occurrences of elements in the schema yet, but I note that Bill's table suggests that category should appear only once - https://docs.google.com/spreadsheets/d/1iHqYHqtuY-sfafEMRGw3nODjVY4BjutYsm0iFRYNJck/edit#gid=1246587534 - should this be implemented in 2.01 (as I will use this occur column as the basis for the schema enforcement).

[ Github issue for implementing this column on the table is now https://github.com/IATI/IATI-Schemas/issues/142 ]

**Comment by Bjwebb** [comment]
@bill-anderson Should multiple category elements be permitted within a document-link ?

**Comment by stevieflow** [comment]
@Bjwebb they can currently (1.04) cant they?  I know @johnadamsdfid does this, for example - as some `document-link` genuinely fit into multiple `category`:

From : http://iati.dfid.gov.uk/iati_files/Country/DFID-Afghanistan-AF.xml

`<document-link url="http://iati.dfid.gov.uk/iati_documents/3606261.doc" format="application/msword">
<title>Logical framework 107171.doc</title>
<language code="en">English</language>
<category code="A02">Objectives / Purpose of activity</category>
<category code="A08">Results, outcomes and outputs</category>
</document-link>`

(which passes schema validation)

**Comment by johnadamsDFID** [comment]
Yes, we do this. As documents can cover multiple categories this needs to be possible. (Otherwise we get marked down by PWYF!)

It also makes sense as a Business Case can contain objectives, budgets, etc, or an Annual Review can contain impact appraisal and results.

**Comment by caprenter** [comment]
@bill-anderson As far as I can tell this change is not mentioned on the support forum for the 2.01 upgrade. 
(http://support.iatistandard.org/forums/21753428-2-01-Integer-Upgrade-Proposals-Current )

**Comment by Bjwebb** [comment]
No, I don't think it is. It's one of the changes that are in Bill's "Iteration 2 Proposal" spreadsheets, but have not yet been implemented, and are not yet on the forum, see https://github.com/IATI/IATI-Schemas/issues/142

**Comment by bill-anderson** [comment]
I incorrectly marked this as (1..1) in the html table, It should be (1..*) and I'm pretty sure it has always been used like this - cf second example at http://iatistandard.org/activity-standard/iati-activities/iati-activity/document-link/category/

**Comment by bill-anderson** [comment]
All done?

**Comment by Bjwebb** [comment]
@caprenter has updated the schema in the [occurs branch](https://github.com/IATI/IATI-Schemas/pull/162) such that the occurs is 1..*

@bill-anderson Not directly related to this issue, but you still need to add the updated table for the activity standard to the support forum proposal.
