### ISSUE TITLE
Implement 2.01 "Redefine activity-website as a document-link"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#118]
http://support.iatistandard.org/entries/76684383-Redefine-activity-website-as-a-document-link

To implement this we need to:
- [x] Remove activity-website element
- [x] Add new codes to the document category codelist

**Comment by Bjwebb** [comment]
@bill-anderson What are the codes/names that should be added to the [DocumentCategory](http://iatistandard.org/codelists/DocumentCategory/) codelist?

**Comment by bill-anderson** [comment]
A code
Activity web page
B codes
Organisation web page
Country/Region web page
Sector web page

**Comment by Bjwebb** [comment]
Should I just use the next availible codes? e.g. A12, B11, B12 and B13?

**Comment by bill-anderson** [comment]
yup

**Comment by Bjwebb** [comment]
Added: http://dev.iatistandard.org/201/codelists/DocumentCategory/
