### ISSUE TITLE
Markup for contact-info/person-name/job-title

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#12]
According to the spreadsheet at https://docs.google.com/a/acclar.org/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1 there will be a new element called

  content-info/person-name/job-title

However, since person-name also allows text content, this will make for messy markup.  Can we make that an attribute instead? e.g.

  content-info/person-name/@job-title

**Comment by caprenter** [comment]
I see what you mean.

I actually think we should stipulate that in each contact info block we have one contact.
So you might have 2 people at one organisation and one at another that you wanted to report. I would say use 3 contact-info blocks.
Then I would put job-title at the same level as person name.

The 'block' is problematic as you could have more than one organisation/person per contact-info block, so  I think that needs to be part of the guidance.

I'm guessing that a job title be in different languages, so having it at the same level as person-name would also help in that case?

**Comment by davidmegginson** [comment]
Yes, @caprenter, that sounds like a reasonable solution.  I'll implement it, then let's take it up with Bill at the next meeting to confirm.

**Comment by davidmegginson** [comment]
Implemented as discussed -- please review, @caprenter, then close if you think it looks OK.

**Comment by caprenter** [comment]
I think this is looking ok - Bill you need to check that this does what you intend. This commit shows test xml near the bottom:
https://github.com/davidmegginson/iati-schemas/commit/a4fee3e3f42683e93b6d283ba63f2230cf3f7c4c

**Comment by bill-anderson** [comment]
Yup, that's what I expected
