### ISSUE TITLE
budget: multiple values and periods are valid

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#121]
Take a look at this file:

http://www.afdb.org/fileadmin/uploads/afdb/Documents/Generic-Documents/IATIOrganisationData.xml

In `recipient-country-budget` multiple `period-start` `period-end` and `value` are published:

``` xml
<recipient-country-budget>
<recipient-country code="CV" xml:lang="en">Cape Verde</recipient-country>
<period-start iso-date="2014-01-01"/>
<period-end iso-date="2014-12-31">indicative country budget, may include non lending operations</period-end>
<value value-date="2014-01-01">13000000</value>
<period-start iso-date="2015-01-01"/>
<period-end iso-date="2015-12-31">indicative country budget, may include non lending operations</period-end>
<value value-date="2015-01-01">69000000</value>
<period-start iso-date="2016-01-01"/>
<period-end iso-date="2016-12-31">indicative country budget,may include non lending operations</period-end>
<value value-date="2016-01-01">5000000</value>
</recipient-country-budget>
```

This validates against the schema.  

However, in practice this makes it difficult to understand which value applies to which period

**Comment by stevieflow** [comment]
On further testing, this seems applicable to budget related elements in org and activity standard

**Comment by Bjwebb** [comment]
Note that once we have [ordering in the schema](http://support.iatistandard.org/entries/76669023-Enforcing-Order-on-the-Activity-Schema), we should be able to enforce this in the 2.01 schema (ie. to make validation fail for the example you posted).

PS, on GitHub it's three backticks for a mutliline quote.

**Comment by Bjwebb** [comment]
This has been fixed in the occurs branch https://github.com/IATI/IATI-Schemas/blob/cbd8234c95ce3e79141efec72c0cc8bc9334d571/iati-organisations-schema.xsd#L405
