### ISSUE TITLE
Ensure full Schema tests coverage

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#128]
@caprenter has updated the activity tests to pass/fail correctly https://github.com/IATI/IATI-Schemas/pull/120, and there's an issue for doing this for the organisation tests https://github.com/IATI/IATI-Schemas/issues/127, but we should also add new tests for new elements etc.

**Comment by Bjwebb** [comment]
Also, we should ensure that language elements are on the correct elements, see https://github.com/IATI/IATI-Schemas/pull/148#issuecomment-52505120

**Comment by caprenter** [comment]
A good amount of work has been done on this for 2.01 - bumping to another milestone

**Comment by caprenter** [comment]
Closing this, as the tests are pretty comprehensive. There may well be more that could be added, but leaving this open is probably not necessary.
