### ISSUE TITLE
Should crs-add/fss/forecast have a value date?

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#13]
Every other use of a monetary amount with a @currency code includes a value date, but the standard doesn't require one for crs-add/fss/forecast (line 339ff).  Can you find out if we should include it here as well?  I won't implement it right now in #4 , but can add it if Bill would like to include it.

**Comment by bill-anderson** [comment]
value date is not there because I took fields direct from the FSS spec

I agree we should add it

**Comment by davidmegginson** [comment]
Added fss/forecast/@value-date as an optional attribute -- I didn't want to make it required, because people filling this in from their old fss might not necessarily have the information available.

@caprenter - please verify, and close if the change is OK.

**Comment by caprenter** [comment]
Looks good to me.
