### ISSUE TITLE
location/administrative/@level - incorrect description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#137]
From @owenscott via: https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit#

This description is incorrect. Most ADM classifications do work this way, but OSM is a notable exception. (and the one that necessitated many of these changes in the first place).```

http://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative#10_admin_level_values_for_specific_countries

I think it would be clearer to say something like

> The system for determining the meaning of each @level value is determined by the @vocabulary being used"

**Comment by bill-anderson** [comment]
"A number defining a subdivision within a hierarchical system of administrative areas. The precise system for defining the particular meaning of each @level value is determined by the @vocabulary being used"

**Comment by stevieflow** [comment]
Thanks.

Will update the guidance note and also assign this to @Bjwebb to edit the schema description accordingly

**Comment by Bjwebb** [comment]
What's the remaining task here? Should this change be backported to 1.05?

**Comment by akmiller01** [comment]
Looks like this change has been successfully made.
