### ISSUE TITLE
Implement 2.01 "Enforcing Order on the Activity Schema"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#138]
http://support.iatistandard.org/entries/76669023-Enforcing-Order-on-the-Activity-Schema [old]

http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements
http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements

**Comment by Bjwebb** [comment]
@bill-anderson I have some queries about this on the KnowledgeBase http://support.iatistandard.org/entries/76669023-Enforcing-Order-on-the-Activity-Schema?page=1#post_26150263

**Comment by bill-anderson** [comment]
@bill-anderson to produce a table for the Knowledge Base listing all elements in order and the (Occurs) for each. Plus accompanying explanation.

**Comment by Bjwebb** [comment]
@bill-anderson Note that this table should probably be produced for both the activity and organisation standards.

**Comment by bill-anderson** [comment]
I know. Won't get there before next week

**Comment by bill-anderson** [comment]
@caprenter you have done organisation, right?

**Comment by Bjwebb** [comment]
@bill-anderson I have enforced the order of the organisation standard (based on the order in [your html table](https://docs.google.com/spreadsheets/d/1AQX74_JN1y68ib0W5RUfS_CGq9MOijaQ2clTxg9kwbE/edit#gid=727726776)). @caprenter has also added the occurs values from the same table , see issue #142

However, enforcing order of the organisation standard is not currently described in the support forum proposal, and probably should be.

**Comment by bill-anderson** [comment]
sigh
yes it should
will aim to get it done friday

**Comment by Bjwebb** [comment]
Thanks, spotted you've posted this now http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements
