### ISSUE TITLE
Activity Date explanation

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#14]
Currently the text within the activity-schema for activity-date is:
Planned starting date for the activity in ISO 8601 date
format, e.g. "2010-10-01".  For the value of the @type
attribute, see
http://iatistandard.org/codelists/activity_date_type

The text content may contain a general date text (e.g. 2011Q1)
for recording less specific dates such as month, quarter, or
year.

I don't think that makes sense (activity dates are not just planned starting dates). 
The text in the spreadsheet on line 40 doesn't help (I think this is about changing the final line):
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

Bill - can you check pls.

**Comment by bill-anderson** [comment]
"The planned and actual start and completion dates of the activity. Start dates may reflect either the commencement of funding, planning or physical activity. End dates should, wherever possible, reflect the ending of physical activity."

This goes into line 37.
Could you also flesh out description in line 38

"Date type (e.g. start-planned, start-actual, end-planned, end-actual)."

**Comment by caprenter** [comment]
Taken some liberties and combined old and new description of an activity date in the schema.
@bill-anderson - can you review and close if happy pls.
