### ISSUE TITLE
Implement 2.01 "Rename crs-add/aid-type-flag"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#140]
http://support.iatistandard.org/entries/29705458-Confusion-Between-Aid-Type-Flag-Type-of-Aid-

**Comment by caprenter** [comment]
Assigning to Bill, as decisions need to be made. The naming of the element is being challenged on the support forum. See: http://support.iatistandard.org/entries/29705458-Confusion-Between-Aid-Type-Flag-Type-of-Aid-

@bill-anderson when a decision is made you can re-assign to me.

**Comment by bill-anderson** [comment]
I think we have consensus that we should rename crs-add/aid-type-flag but NOT what we should call it. I made a proposal which John Adams (correctly) disagreed with. @caprenter @Bjwebb let's discuss tomorrow

**Comment by caprenter** [comment]
We think we should go with the OP's original suggestion of Other Flags

**Comment by Bjwebb** [comment]
To be consistent with our naming scheme, I assume this would make the codelist `OtherFlags` and the element name `other-flags`

**Comment by bill-anderson** [comment]
Is it bad to make the codelist name CRSAddOtherFlags? OtherFlags on its own is a bit otherish

**Comment by Bjwebb** [comment]
No, I don't think that's bad. It's a good idea to reduce ambiguity, and the link between the element and the codelist is now handled by the mapping file, so the element and codelist name don't have to be exactly the same.
