### ISSUE TITLE
Implement occur column for elements from Bill's table

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#142]
[Activity Standard Proposal Table](https://docs.google.com/spreadsheets/d/1iHqYHqtuY-sfafEMRGw3nODjVY4BjutYsm0iFRYNJck/edit#gid=1246587534)
[Organisation Standard Proposal Table](https://docs.google.com/spreadsheets/d/1AQX74_JN1y68ib0W5RUfS_CGq9MOijaQ2clTxg9kwbE/edit#gid=727726776)

These weren't added during Iteration 2 #115 #126 because they require element ordering to implement https://github.com/IATI/IATI-Schemas/issues/138

Note that this is likely to involve additional conditions compared to those described on the Knowledge Base #66 #67 as it lists as mandatory some nested elements (e.g. document-link/category) which had been proposed to be mandatory previously, but this information never made its way into the schema.

[Update: A full updated list of occurs has now been posted on the support forum [Activity Standard](http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements) [Organisation Standard](http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements)]

**Comment by caprenter** [comment]
This work is taking place on the 'occurs' branch ([see this pull request](https://github.com/IATI/IATI-Schemas/pull/162)). The activity schema has been done
https://github.com/IATI/IATI-Schemas/tree/occurs

**Comment by caprenter** [comment]
..and just committed the changes to the organisation schema on the same branch as above

**Comment by caprenter** [comment]
Assigning to @Bjwebb for checking

**Comment by caprenter** [comment]
Just a note - need to implemnt changes in 
https://docs.google.com/spreadsheets/d/1AQX74_JN1y68ib0W5RUfS_CGq9MOijaQ2clTxg9kwbE/edit#gid=727726776 as a result of discussion today.

**Comment by Bjwebb** [comment]
@caprenter And also the changes to the activity standard occurs.

**Comment by caprenter** [comment]
This work has been based on a  spreadsheet that @bill-anderson created. Which is going to be posted in public on the support forum.

**Comment by Bjwebb** [comment]
The occurs list has now been posted on the support forum:
- [Activity Standard](http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements)
- [Organisation Standard](http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements)

Someone should check that these occurs match the generated lists on the dev website:
- http://dev.iatistandard.org/201/activity-standard/summary-table/
- http://dev.iatistandard.org/201/organisation-standard/summary-table/

**Comment by Bjwebb** [comment]
I have checked this, and found that the support forum and schema are consistent for the Organisation Standard, but for the Activity Standard there are the following discrepancies in the forum vs the schema:

```
activity-scope (0..1) vs (0..*)
location-id (0..1) vs (0..*)
administrative (0..1) vs (0..*)
transaction/sector (0..1) vs (0..*)
result/title/narrative (0..*) vs (1..*)
```

For everything except activity-scope, I think the schema is correct (and in fact we actually discussed, and agreed this on a call), so the support forum should be updated to match.

For activity-scope I think the schema is probably incorrect, so needs changing.

@bill-anderson Could you check this is correct?

**Comment by bill-anderson** [comment]
```
activity-scope (0..1)
location-id (0..*)
administrative (0..*)
transaction/sector (0..*)
result/title/narrative (1..*)
```

**Comment by Bjwebb** [comment]
Thanks, @bill-anderson 

I've updated the schema and the support forum proposal so that they're consistent with each other, and with what you've posted here.
