### ISSUE TITLE
location/@ref - unique?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#143]
ref description:

> An internal reference that uniquely describes the location in the reporting organisation’s own system.

Is this unique:
- across all of IATI data
- across the publishers IATI data
- within the specific `iati-activity`

For @bill-anderson 

(Raised by @owenscott at https://docs.google.com/document/d/1I2zoe-_s75kwDKSkU8BRhAZiTy-Fn2FTiaW4BQFUzus/edit# )

**Comment by bill-anderson** [comment]
My take on this was that it was similar to transaction/@ref - i.e. it was for the publisher's own convenience and we had no opinion on its uniqueness.

**Comment by stevieflow** [comment]
@bill-anderson therefore, should the word unique be removed from the schema description?

**Comment by bill-anderson** [comment]
Yes

**Comment by stevieflow** [comment]
Assigned to @Bjwebb to update (in 1.05?)
