### ISSUE TITLE
Inconsistent description of recipient-region/@vocabulary

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#144]
In the schema, for recipient-region/@vocabulary we say:
"The vocabulary from which the region code is drawn. If it is not present 1 - ‘OECD DAC’ is assumed."
https://github.com/IATI/IATI-Schemas/blob/version-1.04/iati-activities-schema.xsd#L296

But on the region vocabulary codelist, 1 is named 'DAC'

@bill-anderson Is one of these more right that an the other? What needs to change please?

**Comment by bill-anderson** [comment]
In all formal descriptions we should always use "OECD DAC"

**Comment by Bjwebb** [comment]
I've changed DAC to OECD DAC in that codelist and in a couple of other places. @bill-anderson Could you double check that these changes make sense: https://github.com/IATI/IATI-Codelists/commit/43d6663da2a20054aa14c3143168cf5fbd8104e3

Note that on the [SectorVocabulary codelist](http://dev.iatistandard.org/201/codelists/SectorVocabulary/) the acronym DAC is spelt out in full (OECD Development Assistance Committee). Ideally we should pick one of these and be consistent, but I think that's a separate issue. Also, codelist names/descriptions probably need reviewing generally.

**Comment by bill-anderson** [comment]
"OECD DAC/CRS" should be replaced with "OECD DAC"

**Comment by bill-anderson** [comment]
"OECD" and "DAC" should be in glossary and not spelt out in Schema

**Comment by Bjwebb** [comment]
I've created a new issue for reviewing names/descriptions of codelists: https://github.com/IATI/IATI-Codelists/issues/45
