### ISSUE TITLE
Tied Status

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#145]
For a start we need to link this post
http://support.iatistandard.org/entries/55170393-Tied-and-partially-tied-values

 into the overview of 2.01
http://support.iatistandard.org/entries/76621773-Version-2-01-Formal-Proposal-Iteration-2-Overview

**Comment by bill-anderson** [comment]
This can be closed? Right?

**Comment by caprenter** [comment]
My understanding is:
The original proposal: http://support.iatistandard.org/entries/55170393-Tied-and-partially-tied-values
'got lost' in 2.01 because it was never referenced as something under consideration in 2.01 from the formal proposal overview posts that @bill-anderson created. We had direct feedback asking "where has it gone"

Now the post (still in 2.01 forum) has detailed some additional guidance for the standard that will clear up the issue. 

The guidance has been committed to _**version-1.05 *_*

All 1.05 changes will be carried over into 2.01.

The only outstanding task I can see is how this change is communicated more widely. The post on the support forum may be enough - but that alone it does not address the original issue where by this item seemed lost in the process because of poor cross referencing.

**Comment by bill-anderson** [comment]
Correction: It didn't get lost. On review of Canada's request I made a judgement call that the current standard caters for their needs. They have now agreed to this. 

The only problem was that the judgement call was not logged and communicated properly

This was an issue for Canada and no one else. If they are now happy there is nothing to do

**Comment by caprenter** [comment]
Cool.
