### ISSUE TITLE
location / administrative - occurs

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#146]
From https://github.com/IATI/IATI-Extra-Documentation/issues/206

occurs should be 0..*

**Comment by bill-anderson** [comment]
Yes. Should be 0..*

**Comment by Bjwebb** [comment]
This has been fixed on the occurs branch https://github.com/IATI/IATI-Schemas/blob/cbd8234c95ce3e79141efec72c0cc8bc9334d571/iati-activities-schema.xsd#L1369
