### ISSUE TITLE
2.01 - organisation schema - recipient-org-budget

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#147]
These doesn't seem a way to insert the name string for an organisation in 2.01 - which might be useful. 

<narrative> isn't supported within this element...

**Comment by Bjwebb** [comment]
Does http://dev.iatistandard.org/201/organisation-standard/iati-organisations/iati-organisation/recipient-org-budget/recipient-org/narrative/ not do what you want?

**Comment by stevieflow** [comment]
Yes, thanks
