### ISSUE TITLE
Scope of activity

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#15]
Bill please confirm!

Add activity Scope element.

Lines 71-73 of the spreadsheet 
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by bill-anderson** [comment]
Confirmed

**Comment by davidmegginson** [comment]
Assigned to David C for verification, and to close the task.
