### ISSUE TITLE
Change the version information in the schemas

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#150]
In the activity, common, organisation, and registry-record schemas, we need to make sure the version information is up to date.

This is both in the description and in the @version attribute

**Comment by caprenter** [comment]
Places this needs updating:
- [x] README.txt
- [x] iati-regisrty-record-schema.xsd
- [x] iati-organisations-schema.xsd
- [x] iati-common.xsd
- [x] iati-activities-schema.xsd
- [ ] CHANGES.txt

**Comment by Bjwebb** [comment]
CHANGES.txt is handled by this https://github.com/IATI/IATI-Schemas/issues/151 and all others have been changed, so closing this issue.
