### ISSUE TITLE
Who maintains the Location Class codelist?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#155]
The [schema currently reads](https://github.com/IATI/IATI-Schemas/blob/64e20cc9cde6f5a04466eeebf934a672e4bf8ca7/iati-activities-schema.xsd#L1494):

> A code from the Location Class codelist (maintained by the US National Geospatial-Intelligence Agency)

However, the Location Class codelist is an Embedded codelist, with no external source mentioned - http://iatistandard.org/codelists/GeographicLocationClass/

@bill-anderson Does one of these need updating?

**Comment by bill-anderson** [comment]
We do.
This was a 1.04 change. It is a simplification of LocationType (category) which is maintained by USNGA.

http://iatistandard.org/codelists/LocationType-category/ shouldn't be there anymore as  1.04 threw it out.

**Comment by Bjwebb** [comment]
Since we maintain it, I'll change the schema description to:

> A code from the Location Class codelist

Also http://iatistandard.org/codelists/LocationType-category/ still exists as it's a useful list for data users who want to categorise LocationTypes in their application.

**Comment by bill-anderson** [comment]
aah
