### ISSUE TITLE
iati-organisation - doesnt permit @version

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#159]
I included the version attribute for 2.01 example XML of the Org file, but this is invalid.

https://github.com/IATI/IATI-Extra-Documentation/commit/2307c8943d073ed2e23748880f5bc23c8b009f5f

http://dev.iatistandard.org/201/organisation-standard/iati-organisations/iati-organisation/

@bill-anderson Should this be included in 2.01 upgrades?

**Comment by bill-anderson** [comment]
2.01 deletes iati-organisations/iati-organisation/@version

**Comment by stevieflow** [comment]
But it says here: http://support.iatistandard.org/entries/76652763-Version-2-01-Iteration-2-6-Improvements-to-the-Organisation-Standard that it is mandatory..?

**Comment by bill-anderson** [comment]
No it doesn't 
???
Ctrl F5??
