### ISSUE TITLE
Recipient-region @vocabulary

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#16]
Bill - please confirm.

Add @vocabulary to recipient-region
Line 80
the spreadsheet
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by bill-anderson** [comment]
Confirmed

**Comment by davidmegginson** [comment]
Assigned to David C for verification, and to close the task.

**Comment by caprenter** [comment]
Good work.
