### ISSUE TITLE
activity schema - ordering

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#160]
`iati-identifier` now seems to be third for `iati-activity` elements, behind `reporting-org` and `participating-org`

Could / should it be first - as the unique/primary identifier for the information that then folows?

**Comment by bill-anderson** [comment]
I am not fussed either way. Happy for @stevieflow and @Bjwebb to agree a call on this

**Comment by stevieflow** [comment]
I vote for 
`iati-identifier` being first
then
`reporting-org`
`title`
`description`

etc

**Comment by Bjwebb** [comment]
@stevieflow If `title` follows `reporting-org`, then where does `participating-org` go?

**Comment by stevieflow** [comment]
@Bjwebb yes.  We've a certain order here: http://iatistandard.org/activity-standard/iati-activities/iati-activity/ - but that doesnt follow the same structure either....!

**Comment by Bjwebb** [comment]
@stevieflow We've suggested a new ordering here http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements which I will now element in the schema.
