### ISSUE TITLE
Only activity description should have @type attribute

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#163]
Also, so that multiple descriptions of different types can be provided, activity description should have occurs 1..*

[Edit: now added to the support forum proposal at the bottom of http://support.iatistandard.org/entries/52106609-Version-2-01-Iteration-3-8-Miscellaneous ]

**Comment by Bjwebb** [comment]
@bill-anderson Could you update the support forum proposal to state that we have removed these `@type` attributes:

```
country-budget-items/budget-item/description/@type
result/description/@type
result/indicator/description/@type
```

**Comment by bill-anderson** [comment]
Done

**Comment by Bjwebb** [comment]
@bill-anderson This is quite a significant change to the schema, so I'd expect to see a note under New Issues on http://support.iatistandard.org/entries/52105759-Version-2-01-Formal-Proposal-Iteration-3-Overview

**Comment by bill-anderson** [comment]
ok

**Comment by Bjwebb** [comment]
Thanks.
