### ISSUE TITLE
2.01 : participating-org/@ref - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#167]
Looking at : http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/participating-org/

> Either @ref or text() must be present.

Is the mention of text() correct?

**Comment by Bjwebb** [comment]
@stevieflow This is generated automatically from the ruleset. Now that we have introduced the narrative element, the mention of text() is incorrect.

Should be:

> Either @ref or narrative must be present.

**Comment by ghost** [comment]
Updated in Spreadsheet. https://docs.google.com/spreadsheets/d/19mRCizDHLuVn5ZfF9b-CJZ0Me4N7ehsmvT2wB4DtipQ/edit#gid=2069246313

**Comment by Bjwebb** [comment]
Have fixed this in the ruleset http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/participating-org/
