### ISSUE TITLE
contact-info/narrative

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#168]
There are narrative element is present for 

`organisation`
`department`
`person-name`
`job-title`
`mailing-address`

Can we please check if multiple `narrative` are allowed on all these?  

Further - does that make sense / use for `person-name` and `mailing-address` ?

**Comment by stevieflow** [comment]
@Bjwebb is it the case that all these narratives can be used multiple times?

**Comment by caprenter** [comment]
The schema does allow multiple narratives on these elements - in fact they are set as type="textRequiredType" - so at least one narrative element must be used.

It may or may not make sense that translations of each of these fields may be supplied, but having the ability to provide a translation is not, I think, a problem.

The 2.01 schema does reflect the will expressed here:
http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements

**Comment by Bjwebb** [comment]
@stevieflow I think it's definitely useful to be able to provide names and addresses in multiple languages. Although many names are the same across some languages, there are often cases where they aren't, most commonly languages that use different writing systems.

**Comment by stevieflow** [comment]
ok thanks

I'll leave translated examples for now - as the purpose of this Issue was to check that they were possible/intended (the will of the standard)
