### ISSUE TITLE
country / region - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#169]
I do think we need to make this simpler, somehow

eg: http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-country/

> The country can also be specified at transaction rather than activity level. If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country and/or recipient-region element AND iati-activity/recipient-region and iati-activity/recipient-region MUST NOT be used AND each transaction MUST only contain one recipient-country or recipient-region.

but need to ask questions first:
- What will the schema do if an activity has three transactions, but only one has an country/region?
- What will the schema do if all transactions have a country, yet iati-activity/recipient-country is also populated?
- What will the schema do if all transactions have a country, yet iati-activity/recipient-region is populated?

**Comment by bill-anderson** [comment]
> > What will the schema do if an activity has three transactions, but only one has an country/region?

Schema won't do anything. Rule will mark it invalid (or whatever rules do)

> > What will the schema do if all transactions have a country, yet iati-activity/recipient-country is also populated?

Schema won't do anything. Rule will mark it invalid (or whatever rules do)

> > What will the schema do if all transactions have a country, yet iati-activity/recipient-region is populated?

Schema won't do anything. Rule will mark it invalid (or whatever rules do)

**Comment by ghost** [comment]
Simplified in spreadsheet https://docs.google.com/spreadsheets/d/19mRCizDHLuVn5ZfF9b-CJZ0Me4N7ehsmvT2wB4DtipQ/edit#gid=2069246313

**Comment by bill-anderson** [comment]
If recipient-country OR recipient-region are reported at the transaction level, ALL transactions MUST contain a recipient-country ~~and/~~ or recipient-region element and iati-activity/recipient-country ~~or~~ and iati-activity/recipient-region MUST NOT be used.
