### ISSUE TITLE
sector - vocabulary - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#170]
The sector narrative description states that this should only be used with RO vocabulary

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/narrative/

This is not mentioned in the vocabulary description text for sector:

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/

**Comment by ghost** [comment]
Updated the sector-vocabulary description in spreadsheet. https://docs.google.com/spreadsheets/d/19mRCizDHLuVn5ZfF9b-CJZ0Me4N7ehsmvT2wB4DtipQ/edit#gid=2069246313

**Comment by bill-anderson** [comment]
Ok
