### ISSUE TITLE
sector - vocabular - description text - citing RO 

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#171]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/

> it is also recommended that if a publisher has its own classification system then the vocabulary “RO” (“Reporting Organisation’s own vocabulary”) should be used

Should this now be `99` ?

And - does `98` need a mention?

**Comment by ghost** [comment]
Updated in spreadsheet changes https://docs.google.com/spreadsheets/d/19mRCizDHLuVn5ZfF9b-CJZ0Me4N7ehsmvT2wB4DtipQ/edit#gid=2069246313

**Comment by bill-anderson** [comment]
Ok

**Comment by caprenter** [comment]
Closed as the fix in #170 covers this
