### ISSUE TITLE
policy-marker / narrative - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#172]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/policy-marker/narrative/

> A description of the policy marker. This MUST ONLY be used where vocabulary = “99 - RO” (the reporting organisation’s own marker vocabulary). May be repeated for multiple languages

Should be updated to include 98?

**Comment by stevieflow** [comment]
See also https://github.com/IATI/IATI-Schemas/issues/171

**Comment by stevieflow** [comment]
Sorry - my bad - 98 doesnt exist on http://dev.iatistandard.org/201/codelists/PolicyMarkerVocabulary/ 

(which is OK?)

**Comment by caprenter** [comment]
@stevieflow Can this be closed then?

**Comment by stevieflow** [comment]
Yes, fixed, thanks
