### ISSUE TITLE
fss - extraction-date - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#177]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/fss/

Just want to double check where this sits with our guidance / instructions on date formats

> The exact date when the information was collected or extracted from donors’ aid management systems. (yyyy-mm-dd plus [optional] timezone)

We dont mention "plus [optional] timezone)" in other cases

**Comment by bill-anderson** [comment]
change it to our standard xsd:date guidelines

**Comment by ghost** [comment]
Found this occurring 11 times in Activity Schema (made changes in spreadsheet to remove optional time zone information). And 6 times in the Organisation Schema (made changes in spreadsheet to remove optional time zone information) - these are all tagged with a note saying "Github #177.
