### ISSUE TITLE
transaction - provider/receiver-org - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#178]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/provider-org/
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/receiver-org/

This doesnt look correct - it only mentions name for the whole description

> The name of the organisation. This can be repeated in multiple languages

There is also a duplication of the word element:

> This element element should occur no more than once (within each parent element).

**Comment by ghost** [comment]
Unclear on first part of this, but have now included logs for removing duplication of the word "element" in both provider- and reciever-org

**Comment by stevieflow** [comment]
now fixed.  Thanks
