### ISSUE TITLE
sector - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#179]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/

> The description of a sector defined by the reporting organisation. (Only to be used when the reporting organisation’s own vocabulary is being used).

This is specifically about `narrative` - and is repeated at http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/narrative/

Should the description text for `sector` be more "generic"?

Also - does there need to be any mention of the fact that sector can be added via transactions?  And , with this - are there any rules similar to https://github.com/IATI/IATI-Schemas/issues/169 ?

**Comment by stevieflow** [comment]
See also https://github.com/IATI/IATI-Schemas/issues/180

**Comment by ghost** [comment]
Since reference to reporting sector at either transaction or activity level has been added to Sector description, I don't think this needs adding to the narrative description. This approach would be consistent with what has been done in other areas of the schema.

**Comment by stevieflow** [comment]
description text now fixed
