### ISSUE TITLE
transaction/sector - percentage ?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#181]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/sector/

Under `vocabulary`:

> NB that if multiple sector codes are used in multiple vocabularies then each vocabulary’s percentages should add up to 100%.

But - there is no `percentage` attribute

**Comment by stevieflow** [comment]
I think this one needs your checking @bill-anderson. 

@izzirbucknall is on the description text issues

**Comment by bill-anderson** [comment]
at transaction level you can have multiple sectors BUT ONLY one sector per vocabulary

**Comment by stevieflow** [comment]
Therefore, the text needs some work/clarity:

> NB that if multiple sector codes are used in multiple vocabularies then each vocabulary’s percentages should add up to 100%.

**Comment by ghost** [comment]
Updated the transaction/sector/vocabulary and transaction/sector descriptions to clarify this. 

https://docs.google.com/spreadsheets/d/19mRCizDHLuVn5ZfF9b-CJZ0Me4N7ehsmvT2wB4DtipQ/edit#gid=2069246313

**Comment by caprenter** [comment]
So should this be changed in the schema, is the suggest text agreed? See also https://github.com/IATI/IATI-Schemas/issues/174

**Comment by bill-anderson** [comment]
Yes
