### ISSUE TITLE
transaction / country / region - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#182]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/recipient-country/

> A country that will benefit from this activity. 

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/recipient-country/

> A supranational geopolitical region that will benefit from this activity. 

Should "activity" be "transaction" ?

Additionally, `transaction/region` states:

> For sub-national geographical location, use the location element.

Read from the perspective of a transaction, this is not true - there is no `transaction/location`

The rest of the text shoudl be clarified and refined alongside https://github.com/IATI/IATI-Schemas/issues/169

**Comment by ghost** [comment]
Updated suggestions on spreadsheet. 

Note that there was discrepancy between use of "transaction" and "activity" between the website and the initial spreadsheet.

**Comment by stevieflow** [comment]
Additionally, I noticed that transaction/country & region states:

> If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country and/or recipient-region element 

The AND/OR could be read as country AND region, perhaps?

It then states:

> each transaction MUST only contain one recipient-country or recipient-region.

We should check that any new description text helps to clarify this @izzirbucknall

**Comment by bill-anderson** [comment]
If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country ~~and/~~ or recipient-region element AND (iati-activity/recipient-country AND  iati-activity/recipient-region MUST NOT be used)
