### ISSUE TITLE
transaction - disbursement channel - order

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#183]
This element is the final child of `transaction`

It might be better to place this before the override child elements (`aid-flow` etc) which are only needed if their value differs from the default.  There is no "default-disbursement-channel" - so it would make it easier to place this element within the "subset" that are unique for a `transaction` - making it easier to provide examples in the documentation.

Ideall, this element should be after `reciever-org` (as sector and country are also not essential, and can be published elsewhere in an activity)

**Comment by bill-anderson** [comment]
So you want it after receiver-org and before sector? I'm happy with that. @Bjwebb ? If you make the change give me go ahead and I will change http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements (which is the non-techie master, right?)

**Comment by stevieflow** [comment]
Assigned to @Bjwebb 

@bill-anderson can you also update the proposal, as you suggest?

**Comment by bill-anderson** [comment]
Done
