### ISSUE TITLE
Source inconsistency: Org Schema/IATI Org/version

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#186]
"iati-organisation/version" element exists in the master spreadsheet (https://docs.google.com/spreadsheets/d/1AQX74_JN1y68ib0W5RUfS_CGq9MOijaQ2clTxg9kwbE/edit#gid=727726776) , but not on the website.

**Comment by caprenter** [comment]
This is marked Red - i.e.for deletion, so is ok.
