### ISSUE TITLE
Source inconsistency: Org Schema/Reporting Org/Secondary Reporter

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#189]
Descriptions are different between website and spreadsheet:

website:

> A flag indicating that the reporting organisation is a secondary publisher: publishing data for which it is not directly responsible. This flag must not be reported by primary source publishers

spreadsheet:

> A flag indicating that the reporting organisation is publishing data for which it is not directly responsible. This flag should not be reported by primary source publishers

**Comment by caprenter** [comment]
Fixed in the spreadsheet
