### ISSUE TITLE
Source inconsistency: Org Schema / Recipient org budget/value

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#191]
Description is different between website and spreadsheet:

Website:

> The total value of the money budgeted to be disbused to the specified recipient organisation during this time period. This element is required.

Spreadsheet: 

> The total value of the money budgeted for the specified organisation for this period.

**Comment by caprenter** [comment]
Fixed in spreadsheet and typo on 'disbused' fixed in schema and removed the words, 'This element is required.' as that can easily be generated.
