### ISSUE TITLE
Source inconsistency: Org Schema/Recipient Country Budget/

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#192]
Different descriptions on website and spreadsheet:

Website

> The recipient-country-budget element allows for the reporting of forward looking budgets for each country in which the organisation operates. The recommendation is that, where and when possible, the organisation’s total annual planned budget for each of the next three financial years is reported for each recipient country. It is strongly recommended that the start and end of the reported financial years match those of the recipient country’s budgetary/planning cycle

Spreadsheet:

> This element represents the total annual budget for a recipient country. The recommendation is that, where and when possible, the organisation’s total annual planned country budget for each of the next three financial years is reported for each recipient country. It is strongly recommended that the start and end of the reported financial years match those of the recipient country’s budgetary/planning cycle.

**Comment by caprenter** [comment]
updated the spreadsheet
