### ISSUE TITLE
Release date needs to be added to each of the 4 schema documents

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#2]
When the release date of the 1.03 version is agreed, this needs to go into the documentation notes of each of the four schema.

**Comment by davidmegginson** [comment]
Clearing assignee for now -- no one can do anything until we know the release date.

**Comment by davidmegginson** [comment]
Since I won't be available next week, I'm assigning this to @caprenter to add the dates when Bill signs off.

**Comment by bill-anderson** [comment]
Is this dev release date or live date?

**Comment by caprenter** [comment]
In the last (1.02) release I altered the date on/just before the day we agreed it was live. It's really a final, final step. so this task can wait. It's not holding up the process now.

**Comment by bill-anderson** [comment]
Ok, great
