### ISSUE TITLE
crs-add/loan-status/repayment-type

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#20]
I'm seeing 
crs-add/loan-status/repayment-type
in the XML

I _think_ this should not be there. 

this IS correct under loan-terms:
crs-add/loan-terms/repayment-type

@bill-anderson & @davidmegginson Should we remove this element?

**Comment by davidmegginson** [comment]
Confirmed that crs-add/loan-status/repayment-type is not in the 1.03 proposed changes at https://docs.google.com/a/acclar.org/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by davidmegginson** [comment]
Confirmed that crs-add/loan-status/repayment-type _does_ appear in iati-activities-schema.xsd

**Comment by davidmegginson** [comment]
Passed to Bill for confirmation that this change was correct.  Please confirm and close.

**Comment by bill-anderson** [comment]
No. I cannot confirm, it should be there.

In the proposed changes as per above gdoc  we have crs-add\loan-terms\repayment-type\text()

crs-add/loan-status/repayment-type should be there and is (incorrectly) missing (apologies)

There is an associated codelist

**Comment by caprenter** [comment]
I'm still not clear.

Are we saying that both elements should be in the schema:
crs-add/loan-terms/repayment-type and
crs-add/loan-status/repayment-type
?

If so this is how what the schema WAS showing before, and that I thought might be a bug. @bill-anderson you are saying this was correct and NOT a bug? (If so how did @davidmegginson manage to get it into the schema if it wasn't in the documentation - it may not matter but !??!)

So @bill-anderson do we need to roll back the removal of this element which was done in https://github.com/davidmegginson/iati-schemas/commit/0fdda51c83ad34213966f1fb4f1063314717229f
?

**Comment by bill-anderson** [comment]
Apologies !!!
I have totally not seen that one is loan-status and one is loan-terms

I can confirm that  crs-add/loan-status/repayment-type should not be in the schema

(still can't believe how my eyes didn't see this)

**Comment by caprenter** [comment]
Great, so the fix is good. I'll close the issue
