### ISSUE TITLE
Source inconsistency: Act Schema/contact-info/mailing-address

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#200]
Descriptions are different:

Website:

> The contact mailing address.This element may occur any number of times.

Spreadsheet:

> The contact mailing address.

**Comment by caprenter** [comment]
The second sentence is generated from the information in the schema when the website is built. This will be fixed when this issue is complete: https://github.com/IATI/IATI-Standard-SSOT/issues/63
