### ISSUE TITLE
Source inconsistency: Act Schema/Transaction/Provider Org

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#207]
Difference in descriptions and repetition of wording:

Website:

> For incoming funds this is the organisation from which the transaction originated. If omitted on outgoing funds the reporting-org is assumed. 
> This element element should occur no more than once (within each parent element).

N.B. Extra "element" needs removing.

Spreadsheet:

> For incoming funds this is the organisation from which the transaction originated. If omitted on outgoing funds the reporting-org is assumed.

**Comment by caprenter** [comment]
This is essentially the same as #223 and will be fixed when that is, so closing this.
