### ISSUE TITLE
Source inconsistency: Act Schema/Transaction/Reciever Org

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#208]
Difference in descriptions, and the duplication of the word "element" in the website:

Website:

> The organisation receiving the money from the transaction (if omitted on incoming funds then the receiver organisation is assumed to be the reporting organisation).
> This element element should occur no more than once (within each parent element).

Spreadsheet:

> The organisation receiving the money from the transaction (if omitted on incoming funds then the receiver organisation is assumed to be the reporting organisation)

**Comment by caprenter** [comment]
This is essentially the same as https://github.com/IATI/IATI-Schemas/issues/223 and will be fixed when that is, so closing this.
