### ISSUE TITLE
@version attribute description

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#21]
The description of @version is different between iati-activities and iati-activity:

iati-activities

> A number indicating the IATI specification version in use.

iati-activity

> A number indicating the IATI specification version in use. Defaults to "1.0" if not specified. It is required to specify this attribute if the document is using features specific to an IATI specification other than the initial 1.0 version.

Should we:

a - align the description around the latter
b - add to iati-activity that the @version here can differ from at iati-activities (or not?)

**Comment by Bjwebb** [comment]
See also the more general discussion of these attributes at https://github.com/IATI/IATI-Schemas/issues/30

**Comment by Bjwebb** [comment]
I think we should do (a) as part of our documentation work for 1.04.

I think (b) needs to go through the upgrades process, see this post - http://support.iatistandard.org/entries/50761977--version-should-be-consistent

**Comment by Bjwebb** [comment]
I note that this still refers to "1.0". Is this a valid version of the standard to be referring to in the version attribute? What are the valid versions? Should this be constrained by a codelist?

**Comment by Bjwebb** [comment]
I note that David has  adjusted 1.0 to 1.01 https://github.com/IATI/IATI-Schemas/commit/818e4d46ce8d90f4e2cc3d206022ffcf3aea7399

**Comment by Bjwebb** [comment]
I've changed the descriptions to be consistent, and created a forum post for the proposals that need to go through the upgrade progress. I think this issue is now resolved, or covered elsewhere.
