### ISSUE TITLE
Source inconsistency: Act Schema/transaction/recipient region

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#210]
Descriptions are different:

Website:

> A supranational geopolitical region that will benefit from this activity. For sub-national geographical location, use the location element. Multiple countries and regions can be reported, in which case the percentage attribute MUST be used to specifiy the share of total commitments across all reported countries and regions. Recipient-region must not be used merely to describe the region of a country reported in recipient-region, but ONLY if the region is a recipient IN ADDITION to the country. Region can also be reported at transaction rather than activity level. If transaction/recipient-country AND/OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country and/or recipient-region element AND iati-activity/recipient-region and iati-activity/recipient-region MUST NOT be used AND each transaction MUST only contain one recipient-country or recipient-region.

Spreadsheet:

> A supranational geopolitical region that will benefit from this transaction. If a specific country is not known the recipient-region element MUST be used. For geographical location, use the location element. If transaction/recipient-country OR transaction/recipient-region are used THEN ALL transaction elements MUST contain a recipient-country or recipient-region element AND iati-activity/recipient-region and iati-activity/recipient-region MUST NOT be used.

**Comment by caprenter** [comment]
The website is more up to date than the spreadsheet in this case
