### ISSUE TITLE
Source inconsistency: Act Schema/crs-add/ aid type flag /significance

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#219]
Descriptions are different:

Website:

> Does this flag apply? If ‘false’ do not report the flag

Spreadsheet:

> A boolean indicating whether the flag applies. If ‘false’ do not report the flag

**Comment by caprenter** [comment]
Fixed in https://github.com/IATI/IATI-Schemas/commit/c49903d90c0c3767848a69288c24821129ed0e83
