### ISSUE TITLE
reporting-org description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#22]
The description text for this element is currently:

The organisation issuing a report (not necessarily involved in the organisation or activity being described). May be a donor, fund, agency, etc. Specifying the @identifier and @role attributes is strongly recommended. May contain the organisation name as content. For the value of the @type attribute, see http://iatistandard.org/codelists/organisation-type For the value of the @ref attribute, see the list of officially-registered organizations at http://iatistandard.org/codelists/organisation

Changes

1 - @identifier is not an attribute - change to @ref

2 - The last sentence should be revised to point people to the guidance:

So - new text proposal:

The organisation issuing a report (not necessarily involved in the organisation or activity being described). May be a donor, fund, agency, etc. Specifying the @ref and @role attributes is strongly recommended. May contain the organisation name as content. For the value of the @type attribute, see http://iatistandard.org/codelists/organisation-type For guidance on constructing the value of the @ref attribute, see http://iatistandard.org/org-ref

**Comment by caprenter** [comment]
@bill-anderson Can you ok this asap? If you are happy we can get this into the schema before Friday.

**Comment by bill-anderson** [comment]
Is this a bit better?

The organisation issuing the report. May be a primary source (reporting on its own activity as donor, implementing agency, etc) or a secondary source (reporting on the activities of another organisation). Specifying the @ref and @role attributes is strongly recommended. May contain the organisation name as content. For the value of the @type attribute, see http://iatistandard.org/codelists/organisation-type. For guidance on constructing the value of the @ref attribute, see http://iatistandard.org/org-ref

**Comment by caprenter** [comment]
If @stevieflow is also happy, I shall commit the change. Looks good to me.

**Comment by stevieflow** [comment]
Happy with the revised words

NB - the URL http://iatistandard.org/org-ref doesnt point anywhere atm - I thought it might be prudent to have this and use it as a forwarding URL to the relevant place - just in case we change things around at the documentation.  If this is a hassle, then can revert

**Comment by bill-anderson** [comment]
We need some documentation on this now - 

http://iatistandard.org/guides/organisation-data/ refers to code lists and therefore needs changing

http://iatistandard.org/guides/organisation-data/organisation-identifiers/ needs some intro to explain DAC codes and ongoing gaps

**Comment by caprenter** [comment]
Ok - great. I can update the schema.
Documentation/websites/redirects etc can be dealt with elsewhere. I can sort out the re-direct, I guess @stevieflow can work on the documentation. Will close this ticket once the new guidence in the xsd is in place.

**Comment by bill-anderson** [comment]
Just need to agree what url you are going to point to. The new one or an existing one. Over to @stevieflow

**Comment by stevieflow** [comment]
Put the URL in the schema, and we can then redirect
