### ISSUE TITLE
Source inconsistency: Act Schema/Repayment first date/iso-date

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#221]
Description error in spreadsheet:

Website: http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/crs-add/loan-terms/repayment-first-date/

> First Repayment Date. The date must be in ISO 8601 format (YYYY-MM-DD). 

Spreadsheet:

> time zo

**Comment by caprenter** [comment]
This is obviously a typo in the spreadsheet. I have fixed it in the spreadsheet.

The description needs a fix in the schema.
