### ISSUE TITLE
Recurring error: "ELEMENT" duplication

### ISSUE THREAD

**Issue by ghost** [IATI/IATI-Schemas#223]
Every time 

> This element should occur once and only once (within each parent element)

occurs in the schema description, the first "element" is duplicated.

**Comment by Bjwebb** [comment]
BTW, this line of text is generated automatically based on the minOccurs and maxOccurs values in the schema. This is currently not clear on the website, which is a UI bug.

Not sure exactly what the text error is here. Is the problem that the word "element" appears twice in the above sentence? I think it's currently grammatically correct, but agree it could be more nicely worded. Do you have a suggested alternative?

**Comment by ghost** [comment]
No, I copied in a corrected sentence I'd typed. On the website it looks like this:

> This element element should occur no more than once (within each parent element).
> e.g http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/location/exactness/

Grammatically etc. its fine.

**Comment by Bjwebb** [comment]
Oh yes, I see now. Thanks.

**Comment by caprenter** [comment]
Fix looks good. Thanks.
