### ISSUE TITLE
2.01 - change description text for recipient-region/recipient-country/sector @percentage

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#229]
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-country/
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/recipient-region/
http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/sector/

As per: https://github.com/IATI/IATI-Extra-Documentation/issues/233#issuecomment-55263623 from @bill-anderson 

> The percentage of total commitments or total activity budget.

**Comment by Bjwebb** [comment]
Have changed the description for those cases you've linked. I haven't changed the other percentage attributes - captial-spend and budget-item
