### ISSUE TITLE
Schema description changes

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#237]
## Non publishing organisations (as participating, receiving or providing orgs)

In https://github.com/IATI/IATI-Schemas/issues/231#issuecomment-56687647 I have identified various schema descriptions that need changing based on [Part 9 of the Iteration 3 proposal](http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers). I've created this new issue to discuss the specifics of the schema definitions.

`participating-org/@ref`, `transaction/provider-org/@ref` and `transaction/receiver-org/@ref` all currently have this definition:

> Machine-readable identification string for the organisation. Must be in the format {Registration Agency} - (Registration Number} where {Registration Agency} is a valid code in the Registration Agency code list and {Registration Number } is a valid identifier issued by the {Registration Agency}. If this is not present then the narrative MUST contain the name of the organisation.

@bill-anderson Should this just be changed to:

> Machine-readable identification string for the organisation. If this is not present then the narrative MUST contain the name of the organisation.

(or do we need more explanation than that?)
# Activity Identifier

`iati-identifier` has this definition:

> A globally unique identifier for the activity. This MUST be prefixed with the IATI organisation identifier for the reporting organisation (reporting-org/@ref) and suffixed with the organisation’s own activity identifier. The prefix and the suffix should be separated by a hyphen "-"

This should be changed to something like:

> A globally unique identifier for the activity.
> 
> This MUST be prefixed with EITHER the current IATI organisation identifier for the reporting organisation (reporting-org/@ref) OR a previous identifier reported in other-identifier, and suffixed with the organisation’s own activity identifier. The prefix and the suffix should be separated by a hyphen "-".
> 
> Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates. 

@bill-anderson Does that look okay to you?

**Comment by bill-anderson** [comment]
Non-publishing orgs: existing definition is ok
Activity: accept your suggestion

BTW, Does the MUST NOT in  "Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates."  imply that this is a rule to be enforced? (Which we can't)

**Comment by Bjwebb** [comment]
@bill-anderson I copied the "MUST NOT" text from the proposal at http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers . I think perhaps it is a rule, which we can't enforce programatically - but it something we could monitor with the dashboard (e.g. look for large removals/additions of identifiers), and enforce manually. I'm planning on adding it to the list of rules art https://github.com/IATI/IATI-Extra-Documentation/issues/250

**Comment by bill-anderson** [comment]
Noted

**Comment by Bjwebb** [comment]
For non-publishing orgs, as we discussed on the call this morning, I think I misunderstood the intent of the proposal:

> It is recommended that non-publishing organisations referred to in participating-org/@ref, transaction/provider-org/@ref and transaction/receiver-org/@ref are assigned valid organisation identifiers, but this is NOT mandatory

From our call, it seems this should be something more like:

> When using the `@ref` attribute in in `participating-org/@ref`, `transaction/provider-org/@ref` and `transaction/receiver-org/@ref` must be a valid organisation identifier. If you do not have one, then the narrative element may be used to describe the organisation.

@bill-anderson Is that okay?

I also think we're also not being explicit about what a publisher should do to reference another publisher using 1.0x, who a non-valid (in 2.01) organisation identifier. Presumably you should use `XI-IATI-THEIRID`, in this case? (Unless they've already committed to using a different identifier e.g. XM-DAC-..., in which case should you use that?)

**Comment by bill-anderson** [comment]
Agree on non-pub org revision

referencing another publisher? definitely a loophole here

If i am on 2.01 and you are 1.01 GB-1 what do I call you? errmm (still thinking ...)

**Comment by bill-anderson** [comment]
Looks like we have three options
1. `<receiver-org @ref="XI-IATI-GB-1">`
2. `<receiver-org @ref="GB-1>`
3. `<receiver-org> <narrative>GB-1 DFID</narrative> </receiver-org>`

1) works for me provided that the search tool being built by Dan et al indexes 1.01 org-ids that don't have prefixes naturally AND with XI-IATI-

Agree?

**Comment by Bjwebb** [comment]
Yes, I think 1) is fine.

@bill-anderson Should this be described in the Schema definition (which is already a bit long), or in Guidance? Does this also need adding to the forum?

**Comment by bill-anderson** [comment]
Guidance
I'm not adding any more to the forum. Other than what has to go into the formal proposal

**Comment by Bjwebb** [comment]
@stevieflow Could you update the Guidance/Extra-Documentation as appropriate? PM me if it's not clear what wants adding.

**Comment by stevieflow** [comment]
Putting this documentation Issue in Extra-Docs on this into Post 2.01 milestone right now - as it is about updating the Overview pages
