### ISSUE TITLE
country-budget-items/budget/item/@percentage - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#238]
(Originally from https://github.com/IATI/IATI-Extra-Documentation/issues/233#issuecomment-55265757)

http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/country-budget-items/budget-item/

> The percentage of the budget allocated to this item. Content must be a positive decimal number between 0 and 100, with no percentage sign.

Clarification is that the word "budget" refers to "country budget" (the parent element).  It may be relevant to adjust the description text accordingly, so we dont confuse between the multiple budgets being talked about.

In the code-example, I do use this text:

> When multiple budget-item elements are declared within a single country-budget-items element, then, for each vocabulary used, the percentage values should sum 100%:

Perhaps this could be used?

Assigning to @izzirbucknall to check first of all, but worth @caprenter looking too

**Comment by caprenter** [comment]
The commit above is not related to this issue (I don't think - my mistake) - Re-assigned to @stevieflow to see what still needs to be done as Izzy is not around.

**Comment by stevieflow** [comment]
@bill-anderson 

Is this more correct, as a schema description for `country-budget-items/budget-item/@percentage`:

> When multiple budget-item elements are declared within a single country-budget-items element, then, for each vocabulary used, the percentage values should sum 100%.

**Comment by bill-anderson** [comment]
Sounds right. 
Yes

**Comment by stevieflow** [comment]
@caprenter could you update the schema accordingly?
