### ISSUE TITLE
budget-line - description text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#239]
(from https://github.com/IATI/IATI-Extra-Documentation/issues/194#issuecomment-56781950)

Suggestion to edit the description text from:

> A breakdown of the total budget into sub-totals. The breakdown is determined by the reporting organisation and described in the narrative. The period covered is the same as that covered by the parent total-budget element.

Added new sentance:

> A breakdown of the total budget into sub-totals. The breakdown is determined by the reporting organisation and described in the narrative. The period covered is the same as that covered by the parent total-budget element.  The sum of budget-line values does not have to equal that of in the parent element.

@bill-anderson to sign off/ adjust

This will apply in three instances of budget-line in the org standard

**Comment by bill-anderson** [comment]
ok
