### ISSUE TITLE
location/location-id - description text change

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#240]
(from @bill-anderson at https://github.com/IATI/IATI-Extra-Documentation/issues/205#issuecomment-56781599)

> A unique code describing the location according to a recognised gazetteer or administrative boundary repository. Administrative areas should only be reported here if the location being defined is the administrative area itself. For describing the administrative area/s within which a more specific location falls the location/administrative element should be used.

This should also be changed in 1.04 & 1.05, alongside 2.01

**Comment by caprenter** [comment]
@Bjwebb has accepted this into 1.04 and merged it into 1.05 and 2.01
