### ISSUE TITLE
Description for exactness code has codes in definition

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#243]
Description for exactness code has codes in definition - this would be inconvenient if we ever altered the codes on the list.
Definition: http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/location/exactness/#iati-activities-iati-activity-location-exactness-code

Codelist: http://dev.iatistandard.org/201/codelists/GeographicExactness/

Can I suggest instead we have:
"A code from the Geographic Exactness Codelist."

@bill-anderson - I'm looking for a descison. Then re-assign to me.

**Comment by bill-anderson** [comment]
Agree
