### ISSUE TITLE
fss not in schema CHANGES.txt

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#25]
It looks like the addition of the new optional element fss is not in the CHANGES.txt - maybe on the assumption that is it a child element of crs-add?

**Comment by caprenter** [comment]
@Bjwebb This is now fixed for 1.04 - but is also a 'bug' in 1.03. Do you have an idea about what should we do about that?

**Comment by Bjwebb** [comment]
I would cherry pick the change to the new `version-1.03` branch, and then update the files at http://iatistandard.org/downloads/ with the new file for 1.03.

**Comment by caprenter** [comment]
I think we can do this, and make sure the changes are in the 1.03 files when 1.04 goes live.

This will mean that the current version of 1.03 is not the same as the one tagged as v1.03 release in the repository. We should notify people that the change has been made on the 1.03 branch.

**Comment by Bjwebb** [comment]
I've cherry picked the commit to the `version-1.03` branch.

Still to be done:
- [x] Update http://iatistandard.org/downloads/CHANGES.txt and http://iatistandard.org/downloads/1.03/CHANGES.txt
- [x] Notify the technical list

**Comment by caprenter** [comment]
Tasks above done.
CHANGES.txt is altered here only:
http://iatistandard.org/downloads/1.03/CHANGES.txt
(by using a copy of: https://github.com/IATI/IATI-Schemas/blob/version-1.03/CHANGES.txt

Notification is written into the announcement email which will accompany launch of 1.04
