### ISSUE TITLE
Document-link title - is it required

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#254]
Currently, document-link in organisation files have titles set to 1..1
in activity files the document-link titles are 0..1

**Comment by Bjwebb** [comment]
Note that this difference also exists on the forum proposal (which may need updating appropriately):
http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements
http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements

**Comment by caprenter** [comment]
Title should be required in both schema

**Comment by caprenter** [comment]
Just awaiting the forum updates as pointed out by Ben

**Comment by caprenter** [comment]
Updated this post: http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements
