### ISSUE TITLE
Document-link language

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#255]
In the organisation schema document -link language is 

``` xml
<xsd:element name="language" minOccurs="0" maxOccurs="unbounded">
```

in the activity schema it is

``` xml
<xsd:element name="language" minOccurs="1" maxOccurs="unbounded">
```

Should they be the same?

**Comment by Bjwebb** [comment]
Note that this difference also exists on the forum proposal (which may need updating appropriately):
http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements
http://support.iatistandard.org/entries/52112469-Organisation-Standard-Order-and-occurrence-of-elements

**Comment by caprenter** [comment]
Should not be required in either schema

**Comment by caprenter** [comment]
Just needs the forum updates as pointed out above now

**Comment by caprenter** [comment]
Update the forum post (http://support.iatistandard.org/entries/52110419-Activity-Standard-Order-and-occurrence-of-elements) - only this post needed the correction
