### ISSUE TITLE
README.txt is out of date

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#26]
Still says 1.02

**Comment by caprenter** [comment]
Confirmed.

Combined with the issue https://github.com/davidmegginson/iati-schemas/issues/25 these  are minor changes that could be applied soon. We have an announcement going out later this week. I propose we fix these 2 issues, but announce that we have altered them since the tagged 1.03 version.

**Comment by Bjwebb** [comment]
Fixed in https://github.com/IATI/IATI-Schemas/commit/98a6aba1f55279c606a495cb79c4267f0307c292
