### ISSUE TITLE
Add new element: crs-add/channel-code

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#274]
This issue is generated from the accepted version 2.02 proposal 'DAC Channel of Delivery': http://support.iatistandard.org/entries/83678719-DAC-Channel-of-Delivery

**Comment by bill-anderson** [comment]
Change description to:

The CRS channel code for this activity. This should only be used for reporting to CRS. The code list contains both organisation types and names of organisations. For non-CRS purposes these should be reported using the participating-org element.
