### ISSUE TITLE
Add new attributes (for flagging humanitarian data): iati-activity/@humanitarian and transaction/@humanitarian

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#277]
This issue is generated from the accepted version 2.02 proposal 'Humanitarian Flag': http://support.iatistandard.org/entries/106937796-Humanitarian-Flag

**Comment by bill-anderson** [comment]
Change transaction/@humanitarian description to:

A process flag to indicate that this transaction relates entirely or partially to humanitarian aid. If the entire activity relates to humanitarian aid this should be reported using iati-activity/@humanitarian, rather than for each transaction.
