### ISSUE TITLE
Add new attribute: participating-org/@activity-id

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#278]
This issue is generated from the accepted version 2.02 proposal 'Add @activity-id attribute to participating-org element': http://support.iatistandard.org/entries/82377659-Add-activity-id-attribute-to-participating-org-element

**Comment by bill-anderson** [comment]
Replace definition with:

A valid activity identifier published by the participating organisation which points to the activity that it has published to IATI that describes its role in this activity.
