### ISSUE TITLE
Percentages as positive decimal

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#3]
Our proposal on percentages as decimals (instead of integers) is here:
http://wiki.iatistandard.org/standard/revision/1.03/changes_specification?&#allow_percentages_to_be_specified_as_decimals

However, percentages should be positive (I think!), do we need a more sophisticated definition where we set minInclusiveValue=0 as well like this example:
http://stackoverflow.com/questions/3853476/how-do-i-define-custom-datatype-in-xsd

**Comment by davidmegginson** [comment]
Possibly, but given how loose our current XSD  validation is in other areas (necessarily, due to XSD technical limitations), we might violate the rule of least surprise by suddenly being extremely strict about some things.

**Comment by caprenter** [comment]
ok - cool, lets just go with a change from 'integer' to 'decimal' then.
