### ISSUE TITLE
Capitalisation of repository title

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#31]
This is inconsistent with all our other IATI- repositories, should it be renamed?

**Comment by caprenter** [comment]
yes

**Comment by Bjwebb** [comment]
So, I guess it should be IATI-Schemas. Shall I go ahead and do this. Can't think of anything that will need updating when this changes, as github seems to redirect everything pretty well.

**Comment by caprenter** [comment]
go for it
