### ISSUE TITLE
Update definition: all @xml:lang attributes

### ISSUE THREAD

**Issue by hayfield** [IATI/IATI-Schemas#336]
Update definition of all `xml:lang` attribute of `iati-activity` to read:

> A code specifying the default language of text in this activity. It is recommended that wherever possible only codes from ISO 639-1 are used.

Update definition of all `xml:lang` attribute of `iati-organisation` to read:

> A code specifying the default language of text in this organisation. It is recommended that wherever possible only codes from ISO 639-1 are used

Update definition of all `xml:lang` attribute of `narrative` to read:

> A code specifying the language of text in this element. It is recommended that wherever possible only codes from ISO 639-1 are used. If not present, the default language is assumed.

**Attributes to update:**

- [x] `iati-activity` (defined in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L170-L173))
- [x] `iati-organisation` (defined in [org](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L104-L107))
- [x] `narrative` (defined in [common](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-common.xsd#L40))

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/3?u=hayfield impact this issue.

**Comment by amy-silcock** [comment]
Change to definitions are as follows:

 iati-activity (defined in activity)

- A code specifying the default language of text in this activity. It is recommended that wherever possible only codes from ISO 639-1 are used.

 iati-organisation (defined in org)

- A code specifying the default language of text in this organisation. It is recommended that wherever possible only codes from ISO 639-1 are used

 narrative (defined in common)

- A code specifying the language of text in this element. It is recommended that wherever possible only codes from ISO 639-1 are used. If not present, the default language is assumed.

**Comment by dalepotter** [comment]
Suggest this change is started after merging of #372, in order to avoid merge conflicts.

**Comment by allthatilk** [comment]
agreed

**Comment by amy-silcock** [comment]
@IATI/devs where are these changes to be logged? I suggest not on every page where @xml:lang attributes occur.
