### ISSUE TITLE
Update definition:  [.//recipient-region/recipient-region-budget/sector] @vocabulary-uri attribute

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#341]
Update definition of [recipient-region/recipient-region-budget] vocabulary-uri attribute to read:

>The URI where this vocabulary is defined. If the vocabulary is 99 (reporting organisation), the URI where this internal vocabulary is defined. While this is an optional field it is STRONGLY RECOMMENDED that all publishers use it to ensure that the meaning of their codes are fully understood by data users.

Update definition of [sector] vocabulary-uri attribute to read:

>The URI where this vocabulary is defined. If the vocabulary is 99 or 98 (reporting organisation), the URI where this internal vocabulary is defined. While this is an optional field it is STRONGLY RECOMMENDED that all publishers use it to ensure that the meaning of their codes are fully understood by data users.

**Values to update**

- [x] `iati-activities/iati-activity/recipient-region/@vocabulary-uri` ([PENDING ISSUE](https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/5))
- [x] `iati-activities/iati-activity/sector/@vocabulary-uri` (defined in [activity](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L647-L648))
- [x] `iati-activities/iati-activity/transaction/recipient-region/@vocabulary-uri` (changed in PR #411)
- [x] `iati-activities/iati-activity/transaction/sector/recipient-region/@vocabulary-uri` (changed in PR #413)
- [x] `iati-organisations/iati-organisation/recipient-region-budget/recipient-region/@vocabulary-uri` (defined in [org](https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-organisations-schema.xsd#L427-L428))

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/5 impact this issue.

**Comment by hayfield** [comment]
This definition works for `sector/@vocabulary-uri`

**Comment by amy-silcock** [comment]
In

- iati-activities/iati-activity/recipient-region/@vocabulary-uri
- iati-organisations/iati-organisation/recipient-region-budget/recipient-region/@vocabulary-uri 

Definition changed to:

- The URI where this vocabulary is defined. If the vocabulary is 99 (reporting organisation), the URI where this internal vocabulary is defined. While this is an optional field it is STRONGLY RECOMMENDED that all publishers use it to ensure that the meaning of their codes are fully understood by data users.
