### ISSUE TITLE
Update defintion: [transaction aid-type/default-aid-type] @code attribute

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#345]
Update definition for transaction aid-type code attribute to read:

>A code from the specified vocabulary.

**Values to update**

- [x] `iati-activities/iati-activity/default-aid-type/@code` 
- [x] `iati-activities/iati-activity/transaction/aid-type/@code`

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/7 impact this issue.

**Comment by amy-silcock** [comment]
Definition changed to:

- A code from the specified vocabulary.
