### ISSUE TITLE
Update definition: result indicator reference @indicator-uri attribute

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#347]
Update definition for result indicator reference indicator-uri attribute to read:

>The URI where this vocabulary is defined. If the vocabulary is 99 or 98 (reporting organisation), the URI where this internal vocabulary is defined. While this is an optional field it is STRONGLY RECOMMENDED that all publishers use it to ensure that the meaning of their codes are fully understood by data users.

**Values to update**

- [x] Update `result/indicator/reference/@indicator-uri` definition

**Comment by hayfield** [comment]
Should probably be grouped with https://github.com/IATI/IATI-Schemas/issues/341 - they're pretty much the same change. The only obvious difference is that this attribute is called something different despite having the same function.

**Comment by allthatilk** [comment]
@hayfield I think it makes sense to keep this with the `result` element integration branch.
