### ISSUE TITLE
Description on location-type is inacurate

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#35]
This is apparently not accurate
"The type of location (e.g. "PCL" for a political entity), from an IATI-defined subset of the UCPD/Aiddata code list. See http://iatistandard.org/codelists/location_type"

**Comment by caprenter** [comment]
location-type is to be deprecated in 1.04 - it is unclear whether or not this text needs to be changed

**Comment by bill-anderson** [comment]
"The type of location (e.g. "PCL" for a political entity) from the feature designation codes maintained by the US National Geospatial-Intelligence Agency."
