### ISSUE TITLE
Introduce a New Transaction Type For Internally Sourced Funds

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Schemas#36]
Raised from Zendesk ticket #1047. Currently, it is not necessary for organisations to report or include funding that comes from their own fundraising ( or similar internal) sources. Therefore should such funding be reported on (and do we perhaps need a new transaction type called locally raised funds, or something)

**Comment by Bjwebb** [comment]
Moved this to the upgrades forum: http://support.iatistandard.org/entries/51286906-Introduce-a-New-Transaction-Type-For-Internally-Sourced-Funds
