### ISSUE TITLE
Update definition: organisation-identifier element

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Schemas#361]
Update definition of organisation-identifier element and organisation-identifier @ref attribute to read:

>Machine-readable identification string for the organisation issuing the report. Must be in the format {RegistrationAgency}-{RegistrationNumber} where {RegistrationAgency} is a valid code in the Organisation Registration Agency code list and {RegistrationNumber} is a valid identifier issued by the {RegistrationAgency}

**Attributes to add**

- [ ] TO ADD

**Comment by hayfield** [comment]
Combining with https://github.com/IATI/IATI-Schemas/issues/339 since they are a single logical group of changes.
