### ISSUE TITLE
Add new @iso-date attribute for the baseline element

### ISSUE THREAD

**Issue by dalepotter** [IATI/IATI-Schemas#364]
Add a new attribute at `iati-activities/iati-activity/result/indicator/baseline/@iso-date`:

The attribute will have type `xsd:date` with occurrence rule `0..1`.

**Tasks:**

- [x] Add tests
- [x] Add `iati-activities/iati-activity/result/indicator/baseline/@iso-date`

**Comment by hayfield** [comment]
Need to see how the changes from https://discuss.iatistandard.org/t/final-technical-proposal-for-the-2-03-upgrade/1097/11 impact this issue.

**Comment by amy-silcock** [comment]
Rule change to: 
The attribute will have type xsd:date with occurrence rule 0..1.

**Comment by allthatilk** [comment]
This one appears to have also been completed.

**Comment by stevieflow** [comment]
I think it worth noting in the schema, or guidance, what is now required for baseline, as we have ``iso-date`` and ``year``

**Comment by andylolz** [comment]
+1, as suggested here: https://discuss.iatistandard.org/t/results-improve-consistency-of-results-standard-included-2-03/874/3

Probably better to create a new issue for this, as I’m a bit doubtful anyone will spot this.
