### ISSUE TITLE
Description For Transcation Type Incoming Funds Is Incorrect

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Schemas#37]
Raised from Zendesk ticket #1047. Currently the description for Incoming Funds on the codelist for Transaction Type states that IF transations only relate to 'external' funds. This is apprantly not the case and IF transactions can be used to describe transfers between accounts or projects within a single organisation

**Comment by Bjwebb** [comment]
Moved this to the upgrades forum: http://support.iatistandard.org/entries/50777388-Description-For-Transcation-Type-Incoming-Funds-Is-Incorrect
