### ISSUE TITLE
Enhance Description of Transaction Type Disbursement

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Schemas#38]
Raised from Zendesk ticket #1047. It is currently not clear what is meant by the text in brackets that describes the Transaction Type of Disbursement on the Transaction Type Codelist. Please could this be clarified

**Comment by Bjwebb** [comment]
http://dev.iatistandard.org/codelists/TransactionType/ 

> Disbursement
> The amount placed at the disposal of a recipient country or agency (in the case of internal development-related expenditures, the outlay of funds)

@bill-anderson could you clarify this?

**Comment by bill-anderson** [comment]
Yes. Needs work. We need the above ODA definition but must add a broader one.(Actually the other way round. Need a broad definition and the include a specific one for CRS reporters)

**Comment by Bjwebb** [comment]
Is improving this definition something that needs to go through the updates forum, or should it just remain as a github issue?

**Comment by bill-anderson** [comment]
Commitments and disbursements are the two with critical cross-overs to CRS. So I would put this into 2.01

**Comment by Bjwebb** [comment]
I've posted this on the zendesk forum for 2.01 - http://support.iatistandard.org/entries/51451257-Enhance-Description-of-Transaction-Type-Disbursement

**Comment by Bjwebb** [comment]
@bill-anderson When do we plan to update the description? I fell like it's possibly slipped through the cracks since it is a code, rather than an XML element, which most of our description changes have been to.

Is there a need/plan to do a compreshensive review of code descriptions like you have done for XML elements?

**Comment by bill-anderson** [comment]
Yes. You are right

**Comment by Bjwebb** [comment]
@bill-anderson I'm assuming you've done https://github.com/IATI/IATI-Schemas/issues/38#issuecomment-39991077 as part of the changes in https://docs.google.com/spreadsheets/d/1gVpcS8DR_-QDB8pxKdPHRuuRPmWs1yIWfBaGAhXDwew/edit#gid=0

**Comment by bill-anderson** [comment]
Yes
