### ISSUE TITLE
country-budget-items/budget-item@percentage

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#39]
This attribute expects percentage, even when there is only one in use.

This should act in the same way as country and sector, in that percentage is only expected when there are multiples of the element within the activity

**Comment by caprenter** [comment]
I think we can remove this requirement in 1.04. It would be backwards compatible (?) and I cannot see any problems with bringing it in line with country and sector.

**Comment by stevieflow** [comment]
Just to confirm - that by "I think we can remove this requirement in 1.04." you mean the requirement that the schema expects a percentage even when there is only one budget-item?

**Comment by caprenter** [comment]
The difference in the xml is:
Sector and recipient-country for example use:

``` xml
<xsd:attribute ref="percentage" use="optional"/>
```

country-budget-items/budget-item uses.

``` xml
<xsd:attribute ref="percentage" use="required"/>
```

I think we could alter that 'required' to 'optional' in 1.04 without any objection.

**Comment by Bjwebb** [comment]
Closing this issue, since any discussion can continue on the pull request - https://github.com/IATI/IATI-Schemas/pull/61
