### ISSUE TITLE
2.0x `participating-org/@ref` description breaks traceability

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Schemas#409]
The v2.0x `participating-org/@ref` [description](http://iatistandard.org/202/activity-standard/iati-activities/iati-activity/participating-org/#attributes) says:

> Must be in the format {Registration Agency} - (Registration Number} where {Registration Agency} is a valid code in the Registration Agency code list and {Registration Number } is a valid identifier issued by the {Registration Agency}. 

So if a participating org has an identifier that doesn’t conform to this format, I shouldn’t use it? Surely that can’t be right – an (old style) identifier is better than no identifier.

**Comment by andylolz** [comment]
This is one for @PetyaKangalova / @amy-silcock, right?

**Comment by andylolz** [comment]
Just to be clear: I think this description is fine for `reporting-org/@ref`. But for `participating-org/@ref`, my data refers to entities outside of my control.

**Comment by amy-silcock** [comment]
If your participating-org ref doesn't conform to the above format, then it should be an organisation who started reporting at version 1.03 if not earlier. And therefore has a valid IATI Org Id as of this codelist: http://iatistandard.org/202/codelists/OrganisationIdentifier/

**Comment by andylolz** [comment]
> And therefore has a valid IATI Org Id as of this codelist

Sounds good. So perhaps the wording should be something like:

> Must *__either be a value on the [OrganisationIdentifier](http://iatistandard.org/202/codelists/OrganisationIdentifier/) codelist, OR__* in the format {Registration Agency} - (Registration Number} where {Registration Agency} is a valid code in the Registration Agency code list and {Registration Number} is a valid identifier issued by the {Registration Agency}.

(Proposed addition in italics).

**Comment by stevieflow** [comment]
Hold on.  http://iatistandard.org/202/codelists/OrganisationIdentifier/ is no longer in use.  These identifiers are long gone / not in the correct format.  It's not a suggestion to actively point to this "list" in 2.0x , is it?

**Comment by amy-silcock** [comment]
I don't think we should. But it does explain why some orgs still have IATI Org IDs which are in a different format.

**Comment by andylolz** [comment]
> These identifiers are long gone

Unfortunately not – they’re still in active use by publishers, as a way to identify themselves. So we can either discourage re-use (and break traceability until the publishers in question update) or allow re-use.

> It's not a suggestion to actively point to this "list" in 2.0x , is it?

Well – we should start by addressing the premise here. @stevieflow @amy-silcock what’s your answer to the question in the description of this issue:

> So if a participating org has an identifier that doesn’t conform to this [the org-id.guide] format, I shouldn’t use it?

**Comment by timgdavies** [comment]
Just a quick note on wording if changes are proposed here. In org-id.guide we use the term 'Organisation Identifier List', as not all the possible lists from which a 'registration number' are drawn are strictly 'Registration agencies'. 

I thought in the linking to org-id.guide that this had been addressed, but realise it may have been missed from the schema. 

In terms of the original question:

> So if a participating org has an identifier that doesn’t conform to this format, I shouldn’t use it? Surely that can’t be right – an (old style) identifier is better than no identifier.

My understanding is that all of the codes on http://iatistandard.org/202/codelists/OrganisationIdentifier/ should be possible to map to a code that **does* follow the updated format.

E.g. OrganisationIdentifier: "41311"  = "[XM-DAC](http://org-id.guide/list/XM-DAC)-41311"

**Comment by andylolz** [comment]
> My understanding is that all of the codes on http://iatistandard.org/202/codelists/OrganisationIdentifier/ should be possible to map to a code that **does* follow the updated format.
> 
> E.g. OrganisationIdentifier: "41311" = "[XM-DAC](http://org-id.guide/list/XM-DAC)-41311"

Aha, I see! So in cases where the participating org self declares an old-style identifier (e.g. 41311), best practice is to derive an org ID for the publisher (e.g. XM-DAC-41311), and use that?

> possible to map

~~One more question: Does the mapping / rules for mapping exist somewhere? I’d love to use it in [org-id-finder](https://andylolz.github.io/org-id-finder/)!~~ Never mind – I think I can figure it out :)

**Comment by timgdavies** [comment]
> Aha, I see! So in cases where the participating org self declares an old-style identifier (e.g. 41311), best practice is to derive an org ID for the publisher (e.g. XM-DAC-41311), and use that?

That's my view - but I think a fairly solid good practice that moves us towards better IDs.

> One more question: Does the mapping / rules for mapping exist somewhere? I’d love to use it in org-id-finder

Not yet - but it is something I'd like to work on for next phase of org-id.guide

**Comment by stevieflow** [comment]
I don't know when http://iatistandard.org/202/codelists/OrganisationIdentifier/ was last refreshed with OECD source list (probably never - only done as a one-off in first version of IATI?) - so would guess that the two are away apart

The numeric references (41311) might easily be pre-fixed with ``XM-DAC``, but the others (eg ``AT-1``) might be more problematic, given that "AT" should actually be "1" !

Elsewhere, I did a mock up of what the a record might look like, should we need to format the  *entire* OECD-DAC channel codes list: https://gist.github.com/stevieflow/37f7df7cda7df5b70749620b464a5064

*However* is'nt most of the ^^ now a tad redundant , given that the OECD DAC now publish this list in XML format: http://vs-web-fs-1.oecd.org/crs-iati-xml/Lookup/DAC_codeLists_iati.xml (via http://www.oecd.org/dac/financing-sustainable-development/development-finance-topics/crs-xml.htm)

**Comment by andylolz** [comment]
Yeah sorry, I shouldn’t have mentioned the OrganisationIdentifier codelist. @amy-silcock rightly explained the historical context, and I got myself muddled up / carried away!

So to revise / sum up: What I was going for was more like this:

> Must __*either be the organisation’s self-declared identifier (in their org file – as per [that @stevieflow IATI discuss post](https://discuss.iatistandard.org/t/getting-to-a-list-of-organisation-references-for-iati-publishers/1060)) OR*__ in the format {Registration Agency} - (Registration Number} where {Registration Agency} is a valid code in the Registration Agency code list and {Registration Number} is a valid identifier issued by the {Registration Agency}.

@timgdavies [has alternate advice](https://github.com/IATI/IATI-Schemas/issues/409#issuecomment-363355169). That is: even if a participating org self-declares an identifier, if it doesn’t follow the org-id.guide format, we can/should refer to them by one that does.

I’m happy with Tim’s way! It’d be nice if the guidance reflected it explicitly (i.e. “don’t put nothing! You can turn that old identifier into a new identifier!”), but it’s not crucial. Getting the “ID migration lookup” (or whatever it’s called) into the next phase of org-id.guide would be a good step forward.

---

> given that "AT" should actually be "1" !

It’s true! [https://api.morph.io/andylolz/dac-crs-codes/data.json?query=SELECT * FROM dac_members WHERE name_en = 'Austria'](https://api.morph.io/andylolz/dac-crs-codes/data.json?key=wFTSIH61nwMjLBhphd4T&query=SELECT%20*%20FROM%20dac_members%20WHERE%20name_en%20%3D%20%27Austria%27)
