### ISSUE TITLE
NDP example for result > indicator /@measure

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#41]
http://iatistandard.org/activities-standard/result/indicator/

Text describes NDP, but this is not on the code list

**Comment by caprenter** [comment]
Do you have a solution/suggestion for how to fix this @bill-anderson

**Comment by Bjwebb** [comment]
Currently the plan is to make the codelist changes as part of the 1.05 upgrade process, so it's just the description that needs changing for 1.04.

**Comment by bill-anderson** [comment]
So we just need new examples with code="1" or "2"??

**Comment by Bjwebb** [comment]
That's been done on the dev site http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/result/indicator/

Propose scrapping "e.g. unit, percentage, NDP." from the schema.
