### ISSUE TITLE
Revise budget description text (and relevant other parts of the standard)

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#415]
Re: https://discuss.iatistandard.org/t/proposal-update-of-budget-element-description-text-in-activity-standard/1216

@bill-anderson suggests: 

> Could we define the existing definition as a bug?

I propose this issue can capture the relevant tasks, which can be posted as new (linked) tickets 

I think the task involves:

- [ ] revise budget description in activity schema: https://github.com/IATI/IATI-Schemas/blob/version-2.02/iati-activities-schema.xsd#L2211
- [ ] revise text in budgets guidance text : https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/overview/budgets.rst
- [ ] revise text in transaction guidance text: https://github.com/IATI/IATI-Extra-Documentation/blob/version-2.02/en/activity-standard/overview/transactions.rst

I'm sure there are other areas, so would be good to check this

**Comment by stevieflow** [comment]
@amy-silcock is there anything I can do to help with ^^ ?

**Comment by stevieflow** [comment]
@amy-silcock this all seems to be merged - but only into 2.02?  I don't think it's in the live documentation yet?

**Comment by andylolz** [comment]
> but only into 2.02

@stevieflow: It’s merged to v2.03, too: #417.

> I don't think it's in the live documentation yet?

That’s true. The site isn’t auto-deployed, and presumably hasn’t been deployed in the last 3 weeks. (I was wondering the same this morning re. IATI/IATI-Guidance#309). I guess someone from @IATI tech team needs to hit the deploy button.

It would be cool (and wouldn’t be too much trouble, I guess) to make travis auto-deploy the site via git hooks, so that the version branches always reflect the current state of the live site. I‘d be interested in looking into this, if it’s something that would be likely to be merged?

**Comment by andylolz** [comment]
> I don't think it's in the live documentation yet?

I wonder if this is related to the fact the build is broken? See IATI/IATI-Standard-SSOT#165. I don’t think the site has been deployed since then.

**Comment by stevieflow** [comment]
Yes, I can't see any update in the live site at http://iatistandard.org/203/activity-standard/iati-activities/iati-activity/budget/ - @amy-silcock @dalepotter @PetyaKangalova please can you post when the site will be deployed?

**Comment by amy-silcock** [comment]
I think all the fixes are now showing. @stevieflow and @andylolz please can you confirm?

**Comment by andylolz** [comment]
@amy-silcock: Apologies for the delay. I don’t really know enough about the details of this ticket to comment…

The changes don’t seem to have been made for v1.0x, but perhaps they weren’t intended to be? @stevieflow will know better than me.

**Comment by andylolz** [comment]
@stevieflow is this ticket fixed? Can it be closed?

**Comment by akmiller01** [comment]
I think this issue is resolved. But the changes introduced this issue: https://github.com/IATI/IATI-Schemas/issues/308

So we can safely close this one.
