### ISSUE TITLE
reporting-org descriptive text needs review

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#42]
"Specifying the @ref and @role attributes..."

reporting-org does not have a @role attribute.

Also we might want to move descriptions about attributes out of element descriptions and into descriptions connected to the attribute itself.

**Comment by Bjwebb** [comment]
General issue for moving descriptions into attributes - https://github.com/IATI/IATI-Schemas/issues/48

**Comment by Bjwebb** [comment]
Fixed by this commit - https://github.com/IATI/IATI-Schemas/commit/e9fed4c4c3719745366886727730566932e3cac8
