### ISSUE TITLE
Small typos identified whilst reviewing rulesets

### ISSUE THREAD

**Issue by amy-silcock** [IATI/IATI-Schemas#424]
* in 2.03 `iati-activities/iati-activity/transaction/recipient-region/@code` the 's' from 'is' is missing
* in all v.2 `iati-activities/iati-activity/policy-marker/narrative` the vocabulary code is "99" and not "99 - RO"

**Comment by andylolz** [comment]
I'm unsure what this ticket refers to. Is it possible that it's on the wrong repo? It may also be resolved now, too.

**Comment by amy-silcock** [comment]
Hi @andylolz, thanks for flagging. We spotted some typos in the schema whilst working on the IATI rulesets, these are yet to be changed.

**Comment by andylolz** [comment]
Right, yes! So, this line references “99 – RO”:

https://github.com/IATI/IATI-Schemas/blob/f5b2b2212bc49e37165424115965bab447d4e4b8/iati-activities-schema.xsd#L886

…and this line is missing an 's':

https://github.com/IATI/IATI-Schemas/blob/f5b2b2212bc49e37165424115965bab447d4e4b8/iati-activities-schema.xsd#L1213

**Comment by amy-silcock** [comment]
Feel free to send over some PRs to fix them if you fancy ;)

**Comment by andylolz** [comment]
> Feel free to send over some PRs to fix them if you fancy ;)

Kk, done! (#432; #433; #434).

**Comment by andylolz** [comment]
I guess this is fixed & can be closed.

**Comment by amy-silcock** [comment]
Thanks @andylolz
