### ISSUE TITLE
Better Describe the Roles of Organisations Publishing On Behalf Of Others

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Schemas#43]
This issue has been raised from zendesk ticket 18. See https://iati.zendesk.com/agent/#/tickets/18

We need to include additional fields within the schema to better describe the role of a publisher who is publishing data on behalf of others. The Activity files needs to support secondary publishers. There are three scenarios that need to be covered:
1. Aggregator publishes a donor activity that it has imported (unchanged) from another aggregator 
2. Aggregator publishes a donor activity that it has imported (unchanged) from the donor 
3. Aggregator publishes a donor activity that it has imported and modified

**Comment by Bjwebb** [comment]
Moved this to the upgrades forum: http://support.iatistandard.org/entries/50764737-Better-Describe-the-Roles-of-Organisations-Publishing-On-Behalf-Of-Others
