### ISSUE TITLE
common schema - percentage

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#46]
Description for percentage in common schema states:

The percentage of the budget allocated to this item.  Content
        must be a positive real number between 0 and 100, with no
        percentage sign.

I think this has to be updated to reflect the changelog in 1.03:

Where used, the @percentage attribute is now designated as a decimal value and no longer as a positive Integer

**Comment by caprenter** [comment]
New text supplied via 
https://github.com/IATI/IATI-Schemas/commit/82849506146c96b510ed527fff52280797b069a5

@bill-anderson please can you review and edit as necessary

**Comment by bill-anderson** [comment]
That's ok
