### ISSUE TITLE
Create Capital Spend element

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#5]
See line 198 of this:
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by davidmegginson** [comment]
Again, change the "percent" attribute to "percentage" for consistency with the rest of the schema.

**Comment by davidmegginson** [comment]
Added per spec, except for the attribute name. @caprenter - please review, and close if the change is OK.

**Comment by caprenter** [comment]
Looks good - again leave open until we have decided on the percentage reference issue

**Comment by caprenter** [comment]
Closing as no change for a couple of weeks. Should be ok.
