### ISSUE TITLE
1.04 Tests - do they need to be improved?

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#50]
Test for pass and fail XML for the new elements in 1.04 should be written.

**Comment by Bjwebb** [comment]
What's the current status of this?

**Comment by caprenter** [comment]
3 'should pass' tests are available in 1.04dev branch. I think this pretty much covers what needs to be done.

**Comment by Bjwebb** [comment]
Can this issue be closed then?

**Comment by caprenter** [comment]
I think there is still the issue that the community has not yet inspected this, or had the chance to inspect it properly.

Maybe we need to change the title a little, but by the release of 1.04 we should be confident we have the right tests in place and that there is agreement on that.

**Comment by Bjwebb** [comment]
Ah, yes, good point.

**Comment by caprenter** [comment]
These should also be added to travis:
https://github.com/IATI/IATI-Schemas/issues/56

**Comment by Bjwebb** [comment]
They've now been added to travis.

Do the 1.04 tests still need checking, or can this issue be closed?

**Comment by caprenter** [comment]
With this issue lying dormant for a while, I'm happy to say that what we have in place will do. Given more time we could revisit this. If anyone else wants to pick this up and check through the tests they would be welcome. Marking this a bitesize, and keeping it open but moving it to a future milestone.

**Comment by akmiller01** [comment]
Closing, as we likely don't need additional tests for v1.04 at this point.
