### ISSUE TITLE
Review and update schema text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#54]
Specifically, the text that is used for SSOT documentation.

Ensure this is precise and concise

Remove links to codelists - see: #53

**Comment by Bjwebb** [comment]
This was done by Bill for 2.01:
https://github.com/IATI/IATI-Schemas/commit/7e368cd822ac927832b9a64a671bdae1643e34bb
https://github.com/IATI/IATI-Schemas/commit/dae264e5fd490fe2b5b20e91409908b3674d8fc6
