### ISSUE TITLE
Deprecated stuff

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#58]
Should there be something added to the schema so that when something is deprecated we can read that from the schema?

So far I think we have deprecated both elements and attributes.

If this was desirable it could go into 1.05 and 2.01 possibly

**Comment by Bjwebb** [comment]
It would be good to have machine readable deprecation information. Ideally this should include the version it was deprecated in.

**Comment by bill-anderson** [comment]
Yes

Deprecated items cannot be removed from the schema - but should be clearly marked

**Comment by caprenter** [comment]
This will not make it into 1.05 and is not needed in 2.01 yet. It clearly needs more thought and work, so switching milestone

**Comment by akmiller01** [comment]
I'm guessing the direction that was chosen here was just to let deprecated elements be automatically discovered via comparing past versions of the schema.
