### ISSUE TITLE
Create country-budget element

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#6]
See line 139 of this:
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by davidmegginson** [comment]
I'm concerned that the XML element name "country-budget" is too similar to "recipient-country-budget" in the organisation schema.  The two have different purposes, and should probably have more-distinct names.

I'm going to propose "country-budget-info" for now, and will put that into the dev branch, but we'll need to discuss this to see if there are any objections.

**Comment by davidmegginson** [comment]
Actually, "country-budget-items" is even more descriptive, so I'll use that in the dev branch (pending discussion).

**Comment by davidmegginson** [comment]
Also using budget-item/@percentage instead of budget-item/@percent for consistency with the rest of the schema.

**Comment by davidmegginson** [comment]
I've added the country-budget-items element to the activities schema.  Please take a look and verify, then close if you think it's OK.

**Comment by caprenter** [comment]
This looks ok to me. I think it just needs some sign off from Bill to make sure it meets what he was thinking, so leaving open for now, but looks good I think.

Also just need to check out the percentages issue.

**Comment by caprenter** [comment]
I'm closing this as I think it looks ok. Please re-open Bill if you have any issues with it.
