### ISSUE TITLE
Broken urls in the schema

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#63]
http://iatistandard.org/codelists/crs-repayment-type
http://iatistandard.org/codelists/repayment-nopa

**Comment by caprenter** [comment]
I believe we need to deal with these via redirects, so:
http://iatistandard.org/codelists/crs-repayment-type
should go to:
http://dev.iatistandard.org/codelists/LoanRepaymentType/
and
http://iatistandard.org/codelists/repayment-nopa
should go to:
http://dev.iatistandard.org/codelists/LoanRepaymentPeriod/

@Bjwebb - do you agree. can you set up re-directs if so?

**Comment by Bjwebb** [comment]
Yes, this sounds like an appropriate solution. I'll set up the redirects.

Longer term, I would suggest the urls should be changed, but we're planning on removing them anyway.

**Comment by Bjwebb** [comment]
http://dev.iatistandard.org/codelists/crs-repayment-type and http://dev.iatistandard.org/codelists/repayment-nopa now redirect correctly.
