### ISSUE TITLE
<supporting-information> is not a good element name

### ISSUE THREAD

**Issue by owenscott** [IATI/IATI-Schemas#64]
The below pertains to iati-activities/iati-activity/location/supporting-information.

The name "supporting-information" was always meant as a placeholder until someone had a better suggestion. The element has a two-value code list: 1. Exact, 2. Approximate. It's supposed to represent the "exactness" of a location. "Approximate" would mean "I don't really know the exact locations for this project, so I just put the name of the province that I know it's in", whereas "Exact" means "this is literally the most specific location that I could put for this project", e.g. the location of specific buildings being constructed.

Any ideas?

**Comment by Bjwebb** [comment]
I don't have any better suggestions. @bill-anderson says [on the forum](http://support.iatistandard.org/entries/30405313-New-Location-Supporting-Information-element) that 'precision' is misleading. Could someone clarify why this is?

**Comment by bill-anderson** [comment]
precision suggests something like how many decimal points in the exact location 

definition, exactness, proximity
??

**Comment by Bjwebb** [comment]
I think `definition` is somewhat vague in the same way supporting-information is. `proximity` suggests an actual distance.

I'm okay with `exactness`.

If we change the name of the element, I suggest we also change the name of the codelist. E.g. for `exactness`, `GeographicSupportingInformation` would become `GeographicExactness`.

**Comment by bill-anderson** [comment]
works for me

**Comment by owenscott** [comment]
exactness is genius.

**Comment by caprenter** [comment]
Missed one change on this - the <name> element inside the codelist xml needs to also chnage to Geographic Exactness:
https://github.com/IATI/IATI-Codelists/blob/version-1.04/xml/GeographicExactness.xml

**Comment by Bjwebb** [comment]
https://github.com/IATI/IATI-Codelists/commit/c34e7eff93492df79115f7a84e47c932634183fe
