### ISSUE TITLE
Implement 2.01 "1. Strengthening the core of the standard"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#66]
http://support.iatistandard.org/entries/45539933-Thematic-content-agreed-by-IATI-Steering-Committee

http://support.iatistandard.org/entries/56799133-Version-2-01-Iteration-1-1-Strengthening-the-Core-of-the-Standard/

Most of these proposals will be implemented by adding new rules to the standard.json ruleset. There is a separate issue there - https://github.com/IATI/IATI-Rulesets/issues/13
### The following constraints are already imposed by the schema:
- For each occurrence of participating-org @role is MANDATORY
- For each occurrence of reporting-org @ref is MANDATORY
### The following constraints can be imposed by the schema:

[sector](http://support.iatistandard.org/entries/22993317-Modify-sector-validation-and-guidance)
- [x] sector/@code is MANDATORY
### The following constraints can not be imposed with the current Rulesets setup:

[reporting-org/@ref](http://support.iatistandard.org/entries/41097678-Modify-reporting-org-ref-validation-and-guidance)
- The agency prefix MUST be a valid code in the IATI code list
- The identifier MUST be the same as that recorded by the publisher on the IATI Registry

[iati-identifier](http://support.iatistandard.org/entries/41097918-Modify-iati-identifier-validation-and-guidance)
- It MUST be globally unique among all activities published by a single reporting organisation

[title](http://support.iatistandard.org/entries/41584666-Modify-title-validation-and-guidance)
- It should contain a meaningful summary of the activity

[description](http://support.iatistandard.org/entries/41584706-Modify-description-validation-and-guidance)
- It should contain a meaningful summary of the activity

[sector](http://support.iatistandard.org/entries/22993317-Modify-sector-validation-and-guidance)
-  If Sector/@vocabulary is not present then the DAC vocabulary is assumed
- Use of DAC codes (either 5-digit or 3-digit) is recommended 

[transaction](http://support.iatistandard.org/entries/55997436-Modify-transaction-validation-and-guidance)
- New activities should not be reported until the initial Commitment is available to be published. (The related rule that at least one transaction must exist in an activity is enforced by rulesets)

**Comment by caprenter** [comment]
re: `reporting-org/@ref` - this is already set as required in the iati-common.xsd - it may not need to be included in a ruleset - although I think you are checking to see if this exists as a way of also verifying that reporting-org exists

**Comment by Bjwebb** [comment]
@caprenter That's correct. It should probably be just `reporting-org` to avoid confusion. However, I think we'll be removing this rule from the rulesets anyway, as we plan to enforce it in the schema instead.

**Comment by Bjwebb** [comment]
During the work on the Iteration 2 proposal, we decided we should introduce ordering https://github.com/IATI/IATI-Schemas/issues/138 in order to enforce mandatory elements in the schema. We therefore need to enumerate the new changes to the schema that are needed, and possibly also remove the relevant rules as redundant.

**Comment by Bjwebb** [comment]
Looking at the updated proposal http://support.iatistandard.org/entries/77284798-Version-2-01-Iteration-2-1-Strengthening-the-Core-of-the-Standard

These are implemented in the schema as part of David's [occurs branch](https://github.com/IATI/IATI-Schemas/pull/162):
- The order in which elements are reported MUST follow the sequence dictated by the Schema.
- Schema cardinality rules are enforced.
- The reporting-org element is MANDATORY.
- reporting-org/@ref - It is mandatory
- The iati-identifier is MANDATORY
- At least one occurrence of participating-org is MANDATORY
- For each occurrence of participating-org @role is MANDATORY
- The title is MANDATORY
- The description is MANDATORY
- At least one occurrence of activity-date is MANDATORY
- sector/@code is MANDATORY

Since these can be tested at the schema level, I will remove them from the standard ruleset - https://github.com/IATI/IATI-Rulesets/issues/17

Can be tested with the current ruleset framework:
- reporting-org/@ref - The identifier MUST only contain alphanumeric characters and hyphen, underscore, colon or period
- iati-identifier - MUST only contain alphanumeric characters and hyphen, underscore, colon or period
- All activities MUST contain a start date: either planned or actual
- For each occurrence of participating-org @ref or text() is MANDATORY **[not sure this is being tested correctly]**
- At least one occurrence of Sector is MANDATORY [at activity or transaction level]

Can not be tested with the current ruleset framework:
- reporting-org/@ref - The agency prefix MUST be a valid code in the IATI code list
- reporting-org/@ref - The identifier MUST be the same as that recorded by the publisher on the IATI Registry
- iati-identifier - MUST be globally unique among all activities published by a single reporting organisation
- Once an activity has been reported to IATI its identifier MUST NOT be changed in subsequent updates
- iati-identifier - MUST be prefixed with the organisation identifier referenced in reporting-org/@ref when the activity was first reported.

Definitional:
- If Sector/@vocabulary is not present then the DAC vocabulary is assumed

Recommendations:
- It is recommended that the title contains a meaningful summary of the activity
- It is recommended that the description contains a meaningful description of the activity
- Use of DAC codes (either 5-digit or 3-digit) is recommended 

Additionally the following rule has been removed from the proposal:
- The organisation-identifier found in reporting-org/@ref MUST be the prefix to the iati-identifier
- [x] This also requires a change to the schema description https://github.com/IATI/IATI-Schemas/blob/version-2.01/iati-activities-schema.xsd#L215
- (transaction is also no longer mandatory, but this has been covered in the occurs changes)

**Comment by Bjwebb** [comment]
Those rules above that can be implemented with the rulesets framework should now be implemented. https://github.com/IATI/IATI-Rulesets/issues/17#issuecomment-54491885

Rules that can't be tested with the rulesets framework will be added as documentation, and then tested with bespoke code: https://github.com/IATI/IATI-Extra-Documentation/issues/250

"Rules" in the definitional and recommendation sections above are not really rules, and I think belong simply in the schema descriptions (where they currently are).

**Comment by Bjwebb** [comment]
Since the work here is now covered by other issues, I am closing this issue.
