### ISSUE TITLE
Implement 2.01 "2. Additional mandatory conditions"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#67]
http://support.iatistandard.org/entries/45539933-Thematic-content-agreed-by-IATI-Steering-Committee

http://support.iatistandard.org/entries/57417568-Version-2-01-Iteration-1-2-Additional-Mandatory-Conditions

The following proposals can be implemented in the schema:
- [x] change the definition of planned-disbursement to say, if it is a single date, then use the period start date. ([discussion](http://support.iatistandard.org/entries/22915067-Modify-planned-disbursement-period-start-Alter-guidance-AND-make-start-date-mandatory))
- [x] @iso-date should be required on period-start and period-end of budget and planned disbursement

The following can not currently be implemented using rulesets:
- [ ] The budget element should be repeated for each year of the activity's duration
- [ ] Each budget should cover a period no longer than 1 year

The rest will be implemented in the standard ruleset https://github.com/IATI/IATI-Rulesets/issues/13

**Comment by Bjwebb** [comment]
During the work on the Iteration 2 proposal, we decided we should introduce ordering https://github.com/IATI/IATI-Schemas/issues/138 in order to enforce mandatory elements in the schema. We therefore need to enumerate the new changes to the schema that are needed, and possibly also remove the relevant rules as redundant.

**Comment by Bjwebb** [comment]
- [x] Transaction should no longer be mandatory - http://support.iatistandard.org/entries/55997436#view-post-26238546

**Comment by Bjwebb** [comment]
Looking at the updated proposal http://support.iatistandard.org/entries/77285258-Version-2-01-Iteration-2-2-Additional-Mandatory-Conditions

These are implemented in the schema as part of David's [occurs branch](https://github.com/IATI/IATI-Schemas/pull/162):
- budget/period-start/@iso-date is MANDATORY and must be a valid ISO format
- budget/period-end/@iso-date is MANDATORY and must be a valid ISO format
- planned-disbursement/period-start/@iso-date is MANDATORY

Since these can be tested at the schema level, I will remove them from the standard ruleset - https://github.com/IATI/IATI-Rulesets/issues/17

Can be tested with the current ruleset framework:
- budget/period-end/@iso-date must be after budget/period-start/@iso-date

Can not be tested with the current ruleset framework:
- The budget element should be repeated for each year of the activity's duration
- Each budget should cover a period no longer than 1 year

**Comment by bill-anderson** [comment]
http://support.iatistandard.org/entries/52417175-Version-2-01-Iteration-3-2-Additional-Mandatory-Conditions

on planned disbursement only period-start is mandatory

**Comment by Bjwebb** [comment]
Those rules above that can be implemented with the rulesets framework should now be implemented. https://github.com/IATI/IATI-Rulesets/issues/17#issuecomment-54491885

Rules that can't be tested with the rulesets framework will be added as documentation, and then tested with bespoke code: https://github.com/IATI/IATI-Extra-Documentation/issues/250

**Comment by Bjwebb** [comment]
Since the work here is now covered by other issues, I am closing this issue.
