### ISSUE TITLE
Update documentation 

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Schemas#7]
Boxes highlighted in yellow need to be altered in the schema from here:
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1

**Comment by davidmegginson** [comment]
Updated all highlighted sections except for the ones covered by the query in #12 

David: please verify and close (pre-version1.03 branch).

**Comment by caprenter** [comment]
I think you missed one documentation update. I've committed it here: 73e1a12570bbc0719e67e944837328c98bf49228 Also I'm getting clarification from Bill that he wants the location documentation changes to stay although we are not doing other changes to that element.

**Comment by caprenter** [comment]
Confirmation from Bill - we need to roll back on any changes under `location` element -including documentation.

**Comment by caprenter** [comment]
We also have 2 new changes on lines 208 and 212 of the google spreadsheet to add/alter

**Comment by bill-anderson** [comment]
Confirm that all changes within <location> go to 1.04. (But recipient-region vocab and activity scope remain)

**Comment by caprenter** [comment]
I don't believe new activity-scope element, nor the @vocabulary attribute to recipient region are in the schema yet.

Bill - can you confirm please that:
Lines 71-73 of the spreadsheet ( https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdDcwRHJxaXgtLWVoY2N5VWt4ck1oeGc#gid=1 )
and 
Line 80
SHOULD be in 1.03.

I am creating new tickets for these:
https://github.com/davidmegginson/iati-schemas/issues/16
https://github.com/davidmegginson/iati-schemas/issues/15

**Comment by caprenter** [comment]
Documentation updated. One or two missing lines found.
Committed here if you want to review: 73e1a12570bbc0719e67e944837328c98bf49228

Documentation will be complete when we know about:
#16
#15

**Comment by bill-anderson** [comment]
(Sorry for delay in replying) 

Yes. SHOULD be in 1.03.
