### ISSUE TITLE
Implement 2.01 "7. Replicate more activity-level elements at transaction level"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#70]
See item 7 in the Thematic content agreed by IATI Steering Committee:   http://support.iatistandard.org/entries/45539933-Thematic-content-agreed-by-IATI-Steering-Committee

http://support.iatistandard.org/entries/57969126-Version-2-01-Iteration-1-7-Replicate-more-activity-level-elements-at-transaction-level
- [x] Sector - http://support.iatistandard.org/entries/41583326-Add-transaction-sector (NB This is probably not the correct link)
- [x] Recipient-region and recipient-country - http://support.iatistandard.org/entries/41585486-Modify-recipient-country-and-recipient-region-merge- (NB This item proposes changes to the elements that may differ from the commit below)
- Tied and partially-tied values - http://support.iatistandard.org/entries/55170393-Tied-and-partially-tied-values - No action required

**Comment by Bjwebb** [comment]
This is now visible on the dev site:
http://dev.iatistandard.org/201/activities-standard/iati-activities/iati-activity/transaction/
http://dev.iatistandard.org/201/activities-standard/iati-activities/iati-activity/transaction/recipient-country/
http://dev.iatistandard.org/201/activities-standard/iati-activities/iati-activity/transaction/recipient-region/
http://dev.iatistandard.org/201/activities-standard/iati-activities/iati-activity/transaction/sector/

However, it's currently achieved by referencing the existing elements within transaction. This means that the same schema description is displayed for the subelements under activity and transaction. This means that under the transaction there is text like:

> A partner country that will benefit from this activity. 

Which might be better as

> A partner country that will benefit from this transaction.

**Comment by Bjwebb** [comment]
We also need to clarify what the `@percentage` attribute means now that these elements are at activity and transaction level. Owen has a proposal for this - http://support.iatistandard.org/entries/41583326-Add-transaction-sector

**Comment by bill-anderson** [comment]
@davidmegginson are you happy with us referencing the same element in different places. I personally prefer this approach to the one we took (eg) with default-aid-type at activity level and aid-type at transaction level.

With this approach the definition would be

The country that benefits from this activity or transaction. This can be recorded at either activity or transaction level. This is not necessarily the country in which the receiver of a transaction is located, but the ultimate recipient of the funds or services.

**Comment by davidmegginson** [comment]
I think that approach can work.  _default-X_ at the activity level has the (modest) advantage that it's more self-documenting — it partly answers the question "what's the difference between _X_ at the activity and transaction level — but I don't think that advantage is compelling enough to decide the question.  You can handle the documentation simply by expanding to something like _"A partner country that will benefit from this activity or specific transaction."_

The one risk to consider is potential user confusion about why we have _activity/default-aid-type_ and _transaction/aid-type_ but _activity/sector_ and _transaction/sector_.  Again, that's not a big deal — as standards mature, they inevitably acquire inconsistencies like that — but there is at least a communications effort involved.  In future major versions of the standard, we might want to consider whether to deprecate (not remove) elements like _default-aid-type_ and allow _activity/aid-type_ in its place.

**Comment by Bjwebb** [comment]
http://support.iatistandard.org/entries/57969126-Version-2-01-Iteration-1-7-Replicate-more-activity-level-elements-at-transaction-level
- [x] If any of these elements is used at transaction level, they must not be used at activity level

**Comment by bill-anderson** [comment]
Noted and added.

**Comment by Bjwebb** [comment]
In order to include appropriate descriptions, these transaction level elements are now defined explicitly instead of by reference.

**Comment by Bjwebb** [comment]
Additionally, `@percentage` is not being replicated at transaction level.

For more information, see the [updated section 7 of the Iteration 2 proposal](http://support.iatistandard.org/entries/77287178-Version-2-01-Iteration-2-7-Replicate-more-activity-level-elements-at-transaction-level) and the [recent discussion about transaction/sector](http://support.iatistandard.org/entries/41583326-Add-transaction-sector).

**Comment by Bjwebb** [comment]
The outstanding issue here is implementing: https://github.com/IATI/IATI-Schemas/issues/70#issuecomment-45503856

> If any of these elements is used at transaction level, they must not be used at activity level

This is problematic because this can not be enforced using the Schema, or the current Rulesets framework. The options are:

1) Modify the rulesets framework to allow this to be enforced. This is potentially over complex for this simple rule.
2) Create an independent test for this on the dashboard
3) Don't check it by machine at all.

Note that this is solely an issue of implementing this for machines. For people the description of this rule is already contained within the schema http://dev.iatistandard.org/201/activity-standard/iati-activities/iati-activity/transaction/recipient-country/

This is similar to https://github.com/IATI/IATI-Schemas/issues/109#issuecomment-50470323

**Comment by caprenter** [comment]
Assigning to @bill-anderson  to make a decision.

**Comment by bill-anderson** [comment]
We need a machine rule.
This is easier if we modify the rule slightly, by saying:
- If activity-level element exists then this overrides transaction-level
- If activity-level is not present then transaction-level is mandatory

**Comment by caprenter** [comment]
@bill-anderson would you be able to reply to the comment on this post please:
http://support.iatistandard.org/entries/77287178-Version-2-01-Iteration-2-7-Replicate-more-activity-level-elements-at-transaction-level

**Comment by bill-anderson** [comment]
Done [updating the support forum]

**Comment by Bjwebb** [comment]
> We need a machine rule.
> This is easier if we modify the rule slightly, by saying:
> - If activity-level element exists then this overrides transaction-level
> - If activity-level is not present then transaction-level is mandatory

@bill-anderson Is that actually easier? Isn't it easier to just say "Must be reported at activity level or transaction level but not both.". If we do want to change this rule, does the forum also need changing?

**Comment by bill-anderson** [comment]
Isn't it easier to just say "Must be reported at activity level or transaction level but not both.". 
Yes, I agree

If we do want to change this rule, does the forum also need changing? 
Yes I will change now

**Comment by bill-anderson** [comment]
NB this works for sector (which I have changed) but NOT region and country which has a few more and/ors

**Comment by Bjwebb** [comment]
@bill-anderson Have you made the change on the forum? I can not see it at http://support.iatistandard.org/entries/52106549-Version-2-01-Iteration-3-7-Replicate-more-activity-level-elements-at-transaction-level

**Comment by bill-anderson** [comment]
Who pointed me to http://support.iatistandard.org/entries/77287178-Version-2-01-Iteration-2-7-Replicate-more-activity-level-elements-at-transaction-level

Doh

Done

**Comment by Bjwebb** [comment]
@bill-anderson David did. But in a comment posted at the start of August!

Where should I be getting the rule for region/country from, is it what's written in the schema description? If it is from the schema description, are there other rules written into the schema, that need need adding to http://dev.iatistandard.org/201/rulesets/standard-ruleset/#non-machine-readable-rules?

Also, how does the rule apply to reporting sectors of different vocabularies? Must every vocabulary be reported at the same level (this is what the current rule implies).

**Comment by bill-anderson** [comment]
Actually this does work

Either recipient-country or recipient-region MUST be reported at activity level or transaction level but not both.

Doesn't it?

**Comment by Bjwebb** [comment]
@bill-anderson Yes, that does work. Can I just double check we are making these mandatory in 2.01, as they're not mentioned [here](http://support.iatistandard.org/entries/52105879-Version-2-01-Iteration-3-1-Strengthening-the-Core-of-the-Standard), whereas sector is.

**Comment by bill-anderson** [comment]
Yes

I will add to the proposal in Strengthning the Core section

**Comment by Bjwebb** [comment]
Thanks, have added the rules to http://dev.iatistandard.org/201/rulesets/standard-ruleset/#non-machine-readable-rules

Assigning to @bill-anderson , to update the proposal.

**Comment by Bjwebb** [comment]
@bill-anderson BTW, not sure I've had an answer to this question:

> Also, how does the rule apply to reporting sectors of different vocabularies? Must every vocabulary be reported at the same level (this is what the current rule implies)?

**Comment by bill-anderson** [comment]
Not sure what that means. If you mean you can report one vocabulary at activity-level, and another at transaction-level, definitely not.

""Must be reported at activity level or transaction level but not both." doesn't allow that

**Comment by Bjwebb** [comment]
Yes, current rule does not allow it. I was asking whether we should allow it - it seems like something publishers might want. Happy to leave as is though.

**Comment by bill-anderson** [comment]
Definitely don't want to do make it complicated

**Comment by caprenter** [comment]
So @bill-anderson what is the action here?

**Comment by Bjwebb** [comment]
Action from Bill's most recent clarification is to do nothing, I was simply asking whether it should be different.

Outstanding action on this issue is for Bill to update the Strengthening the Core section of the proposal https://github.com/IATI/IATI-Schemas/issues/70#issuecomment-57175082

**Comment by Bjwebb** [comment]
@bill-anderson Has the proposal been updated with this change?
