### ISSUE TITLE
Description text for org standard

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#72]
This would need adding to the org schema for iati-organisation

> The Organisations Standard allows publishers to report on information for multiple organisations: a government agency may report on behalf of other agencies; an INGO may report on behalf of its national associates; a private company may report on behalf of its subsidiaries. The Record Header, the iati-organisation element, indicates the start of a report on a single organisation’s information.

It is currently here: http://iatistandard.org/organisation-standard/record-header/

But not in the SSOT: http://dev.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/

The iati-organisations element does not have any descriptive text in the old website: http://iatistandard.org/organisation-standard/file-header/ - but it might be a good idea to balance this text between iati-organisations/iati-organisation accordingly

**Comment by Bjwebb** [comment]
@bill-anderson Could you confirm that this text is still correct, and that it makes sense to include it in the schema for 1.04.

**Comment by bill-anderson** [comment]
Yes

**Comment by stevieflow** [comment]
Would advise editing slightly

`iati-organisations` 

> The Organisations Standard allows publishers to report on information for multiple organisations: a government agency may report on behalf of other agencies; an INGO may report on behalf of its national associates; a private company may report on behalf of its subsidiaries. The `iati-organisations` element acts as a container for this possibility.

For `iati-organisation`

> Indicates the start of a report on a single organisation’s information.

**Comment by Bjwebb** [comment]
`iati-organisations` looks good.

For `iati-organisation` - I think that these definitions should be for XML elements, which encapsulate information (rather than XML tags which indicate the start/end). Therefore I would suggest keeping the description as it is:

> Top-level element for a single IATI organisation report.

This is consistent with how we describe `iati-activity` http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/

**Comment by stevieflow** [comment]
Agree

I ve put the more verbose text into this overview page: https://github.com/IATI/IATI-Extra-Documentation/commit/5bca6e5a663a4cc2459c2472ebb70b2b7cc4bb49

**Comment by Bjwebb** [comment]
I think the inclusion of that text in the Overview page resolves this issue.
