### ISSUE TITLE
Organisation name - remove name dropping

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#73]
Along with the policy of removing name dropping - the name description needs revising:

> The human-readable name of the organisation (e.g. “Doctors without Borders”). This element may be repeated to provide the name in different languages (using @xml:lang to distinguish).

Suggestion - take out " (e.g. “Doctors without Borders”)" entirely (as code examples will be given).

**Comment by Bjwebb** [comment]
More general namedropping issue: https://github.com/IATI/IATI-Extra-Documentation/issues/1

**Comment by Bjwebb** [comment]
I've implemented your suggestion.
