### ISSUE TITLE
No mention that at least one sub-element is expected in document-link

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#75]
Here: http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/document-link/

Validation always expects one of the sub-elements

**Comment by Bjwebb** [comment]
This is true of other elements, such as iati-activity

**Comment by bill-anderson** [comment]
Is this not one of (many) conditional validations. For every document-link element there must be a url, a title and a category. The schema can't do this, right?

**Comment by Bjwebb** [comment]
The schema currently requires that document-link and iati-activity have at least one subelement.

**Comment by bill-anderson** [comment]
Which is not very helpful. So to repeat my question above: the schema can't handle what we need and we need additional conditional logic?

**Comment by Bjwebb** [comment]
Correct, this is what https://github.com/IATI/IATI-Rulesets/blob/version-1.04/rulesets/standard.json is for.

**Comment by stevieflow** [comment]
If I try to validate:

``` xml
<iati-activities generated-datetime="2014-04-03T18:27:37" version="1.03">
  <iati-activity default-currency="EUR" last-updated-datetime="2014-04-03T18:27:37" xml:lang="en">
      <document-link format="application/odt" url="http:www.example.org/docs/project.odt"/>
  </iati-activity>
</iati-activities>
```

I get a response of

5   Error 1871  Element 'document-link': Missing child element(s). Expected is one of ( title, category, language, ##other\* ).

My original question (maybe not clear) was how we display this via the SSOT into iatistandard.org

**Comment by Bjwebb** [comment]
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/document-link/

Now contains the line:

> The schema states that this element must have at least 1 subelement.
