### ISSUE TITLE
organisation / total-budget - different descriptions

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#76]
Via the schema, and so in the SSOT:

> This element represents the organisation’s total planning budget for a calendar period (typically, but not necessarily, a year). This element may be repeated for each period described (normally, periods should be consecutive).

In the website (entered manually)

> The total-budget element allows for the reporting of the organisation’s own budget. The recommendation is that, where and when possible, the organisation’s total annual planned budget for the next three years is reported.
> 
> The element is repeated for each reported year. It is possible to report periods other than years, but this is not recommended.

The latter will be lost when we move to SSOT.  @bill-anderson please advise accordingly

**Comment by bill-anderson** [comment]
The total-budget element allows for the reporting of the organisation’s own budget. The recommendation is that, where and when possible, the organisation’s total annual planned budget for each of the next three years is reported.
