### ISSUE TITLE
organisation / org-budget - different descriptions

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#77]
In Schema / SSOT:

> This element represents the budget for disbursements to another organisation (such as an institution funded by a national donor).

In (current) live site - this text will be lost if not incorporated into schema:

> Annual forward planning budgets for funded institutions
> 
> Definitions
> 
> The recipient-org-budget element allows for the reporting of forward looking budgets for each institution (i.e. multiliateral, INGO, foundation) which receives core funding from a donor. The recommendation is that, where and when possible, the donor’s annual planned budget for the next three to five financial years is reported for each recipient institution.

Flagging for @bill-anderson initially

**Comment by bill-anderson** [comment]
The recipient-org-budget element allows for the reporting of forward looking budgets for each institution (e.g. multiliateral, INGO, foundation) which receives core funding from a donor. The recommendation is that, where and when possible, the donor’s annual planned budget for each of the next three financial years is reported for each recipient institution.

(NB ... for each of the next three financial years ...)

**Comment by Bjwebb** [comment]
The description of `recipient-org-budget` has been changed in 2.01 https://github.com/IATI/IATI-Schemas/blob/cc62db20dc6cc04081977dee3c5f2cc30d0c951f/iati-organisations-schema.xsd#L252, but isn't the same as the description above.

@bill-anderson What's the intent here? Should the extra wording be added to the schema, or should it be incorporated into Extra-Docs/Guidance instead?

**Comment by bill-anderson** [comment]
2.01 should be as above

i.e.

The recipient-org-budget element allows for the reporting of forward looking budgets for each institution (multiliateral, INGO, foundation, etc) which receives core funding from a donor. The recommendation is that, where and when possible, the donor’s annual planned budget for each of the next three financial years is reported for each recipient institution.

**Comment by stevieflow** [comment]
@bill-anderson with regards to the above description, it would suggest _not_ to use `recipient-org-budget` when publishing IATI further down the "chain" ?

**Comment by bill-anderson** [comment]
The distinction is between core funding and activity-earmarked funding

**Comment by stevieflow** [comment]
So - this is _only_ to be used by donor type organisations (how do we qualify that?)?

Regardless - can we clarify if the description at 

http://iatistandard.org/organisation-standard/iati-organisations/iati-organisation/recipient-org-budget/

> This element represents the budget for disbursements to another organisation (such as an institution funded by a national donor).

is correct or not, as far as 1.04 goes?

**Comment by bill-anderson** [comment]
No, it is not correct.

The recipient-org-budget element allows for the reporting of forward looking budgets for each institution  which receives core funding from the reporting organisation. The recommendation is that, where and when possible, annual planned budgets for each recipient institution for each of the next three financial years are reported. This is primarily applicable to donors but any provider of core funding is expected to use it. Earmarked budgets should be reported at activity-level through the Activity Standard.

**Comment by stevieflow** [comment]
@bill-anderson so @Bjwebb needs to edit the schema description for 1.04?

**Comment by bill-anderson** [comment]
Yes (or 1.05 if easier)

**Comment by Bjwebb** [comment]
@bill-anderson Could you clarify whether your most recent long paragraph of text is the suggested new description (for 1.04/1.05 and 2.01), or just explanation for Steven?

This can go into 1.04 if we consider it to be a bug fix / documentation change.

**Comment by bill-anderson** [comment]
Yes, new description. Can go into 1.04
