### ISSUE TITLE
organisation / recipient-country-budget - different descriptions

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#78]
In SSOT / Schema:

> This element represents the budget for disbursements to a specific country across all projects.

In current live site:

> Annual forward planning budgets for recipient countries
> 
> Definitions
> The recipient-country-budget element allows for the reporting of forward looking budgets for each  country in which the organisation operates. The recommendation is that, where and when possible, the organisation’s total annual planned budget for the next three to five financial years is reported for each recipient country. It is strongly recommended that the start and end of the reported financial years match those of the recipient country’s budgetary/planning cycle.

Flag for @bill-anderson initially

**Comment by bill-anderson** [comment]
The recipient-country-budget element allows for the reporting of forward looking budgets for each country in which the organisation operates. The recommendation is that, where and when possible, the organisation’s total annual planned budget for each of the next three financial years is reported for each recipient country. It is strongly recommended that the start and end of the reported financial years match those of the recipient country’s budgetary/planning cycle.

(NB change - " ... for each of the next three financial years..."
