### ISSUE TITLE
iati-identifier is used in organisation schema

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#79]
But in the description:

> A globally unique identifier for this activity. 

http://dev.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/iati-identifier/

**Comment by caprenter** [comment]
I propose:

> The iait-identifier element is used in both Activity files and Organisation files, and has a slightly different meaning depending on where it is being used, and should not be confused.
> 
> When used in an organisation it is a globally unique identifier for that organisation.
> 
> When used in an activity it is a globally unique identifier for that activity. This should be in the form of the IATI Organisation Identifier (for the reporting organisation) concatenated to that organisation's activity identifier. (NB. Two or more reporting organisations may publish information on the same activity. To cross-reference these reports the other-identifier element should be used.)

**Comment by bill-anderson** [comment]
That's really bad. I suggest that in 2.01 organisation standard is changed and iati-identifier is renamed iati-organisation-identifier

**Comment by caprenter** [comment]
I've already added this is an issue on the modifications etc forum:
http://support.iatistandard.org/entries/50478433-Better-treatment-of-iati-identifier-in-the-schema

**Comment by Bjwebb** [comment]
How do we fix this in 1.04? We could change the description to "A globally unique identifier for this activity or organisation.", but I think this might be actively confusing in the activity standard. Alternatively, we could change the reference in the organisation schema (at https://github.com/IATI/IATI-Schemas/blob/version-1.04/iati-organisations-schema.xsd#L70) into its own element, with it's own description (I know doing this kind of thing is frowned upon in schemas, but it may be the less bad option).

**Comment by bill-anderson** [comment]
I would change the description - but a bit more than you have. Say something like "not to be confused with ..."

**Comment by Bjwebb** [comment]
Oops, ignore my above comment, I'd missed @caprenter's proposal, which I agree with. @bill-anderson Not sure what you're suggesting, @caprenter's "not to be confused" is referencing the two usages mentioned earlier in the sentence.

**Comment by bill-anderson** [comment]
What I meant was ...
I think in 2.01 we should change the organisation's element name, 
In 1.04 we should just point out in the description that there is a danger of confusion

**Comment by Bjwebb** [comment]
Okay, thanks for the clarification. I've used David's proposed description, which is now visible at http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/iati-identifier/ and http://dev.iatistandard.org/organisation-standard/iati-organisations/iati-organisation/iati-identifier/
