### ISSUE TITLE
New git branches

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#8]
David: I've created two new git branches:
- relaxng - my old work in progress on switching to RelaxNG (saved for future use)
- pre-version1.03 - branch for our work getting ready for version1.03 (rather than using master)

Are these OK with you?  Please feel free to rename them, if not.

**Comment by caprenter** [comment]
Hi Dave

I've already set up a 1.03dev branch and made a few 'getting started' commits for you to review. I did these a couple of days ago. I'm not precious about the naming etc, but you might want to pull those commits in, or switch branches.

I was just starting to reference the commits to the wiki as well.

**Comment by davidmegginson** [comment]
I've merged my changes into 1.03dev, tested, and pushed.  That's now our working branch.  I've removed pre-version1.03 after the move.
