### ISSUE TITLE
Remove all urls of organisation codelist

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#80]
Since we are retiring this list, as described at http://support.iatistandard.org/entries/28497976-Retire-the-Organisation-Identifier-codelist

http://iatistandard.org/codelists/organisation should be removed from the Schema.

There is also http://iatistandard.org/org-ref which currently redirects to the above, but I believe that @stevieflow wants to make this the new page that explains how you should obtain/use organisation references.

**Comment by caprenter** [comment]
I think this can be bumped to after 1.04 is released. The list still exists, and we have further discussion/plans for removing other URLs from the schema.

**Comment by Bjwebb** [comment]
I think in this case it might be worth looking at for 1.04 because the schema says values should be on the codelist, when this is no longer true. At the very least we need to male sure there's an appropriate message on the organisation codelist page in 1.04

**Comment by Bjwebb** [comment]
Following discussion with @caprenter on Skype, I have removed the text referencing the organisation codelist.
