### ISSUE TITLE
other-identifier - differences in definition

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#83]
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/iati-identifier/

> Two or more reporting organisations may publish information on the same activity. To cross-reference these reports the other-identifier element should be used

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/other-identifier/

> An alternative, non-IATI identifier for the activity. This identifier is not guaranteed to be unique or persistent (it depends on the owner organisation’s policies, not IATI’s).

**Comment by bill-anderson** [comment]
We need to clarify this definition in conjunction with related activity,

My preference is for the latter and another code in related-activity-type to indicate "another publisher's report on the same activity"

**Comment by stevieflow** [comment]
@bill-anderson thanks

The suggestion for another code cannot be covered in 1.04 - but I think we need to clarify this sooner

Are you suggesting that we centre guidance on it being a non-IATI identifier?

I could post in the modification forum in terms of a proposal around the extra `related-activity` code

**Comment by bill-anderson** [comment]
Agree that in 1.05 we add a related-activity code which defines an id for the same activity published by someone else

For now can we just leave out the sentence  "To cross-reference these reports ..."?

**Comment by stevieflow** [comment]
Thanks

Have added to upgrades forum: http://support.iatistandard.org/entries/54201556-related-activity-new-code

@Bjwebb can you edit schema text?

**Comment by Bjwebb** [comment]
@bill-anderson Just to note that, in the Annual Report, `other-identifier` is referred to as "Other IATI Identifier"

**Comment by bill-anderson** [comment]
Noted - where do we log this to remember to change ...

**Comment by stevieflow** [comment]
@bill-anderson : http://support.iatistandard.org/entries/54201556-related-activity-new-code
