### ISSUE TITLE
sector - link to codelist

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#85]
The description for sector in the schema:

> Sector code and name. For the value of the @code attribute, see http://iatistandard.org/codelists/sector Either the @code attribute or descriptive text content must be present.

This link is not correct - (should be /Sector) - but would be better to tidy this up

**Comment by Bjwebb** [comment]
The link is fine. It's based on the current URLs which are fine, but the redirect is broken atm, which I will fix. The longer term solution to this is removing the codelist urls from the schema, as we have the mapping file. However, we decided to not do this in 1.04 https://github.com/IATI/IATI-Schemas/pull/57

Is there any other tidy up you want to do, or is this issue fixed once I fix the redirect?

**Comment by Bjwebb** [comment]
The redirect on the dev website has been fixed now.
