### ISSUE TITLE
defaults - ordering

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#86]
In the schema (as observed at http://dev.iatistandard.org/activities-standard/)

we have

default-finance-type
default-flow-type
default-aid-type
default-tied-status

Within a `transaction` we then have:

flow-type
aid-type
finance-type
tied-status

It would be preferable to have the two aligned in terms of ordering.

**Comment by bill-anderson** [comment]
Agree, in which case they should be logically ordered as

flow
finance
aid
tied
