### ISSUE TITLE
Project or Activity?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#87]
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/contact-info/

Schema says

> Contact information for the project. Specify whatever is available. You may repeat this element for each contact person.

project should be activity

**Comment by bill-anderson** [comment]
Agree

**Comment by Bjwebb** [comment]
I've fixed this, but noticed other similar usages in the activities schema:
`activity-status` - "The current status of the project"
`budget` - "The value of the aid activity's budget for each financial year as in the original project document."
`collaboration-type` - "The type of collaboration involved in the project's disbursements, e.g. "bilateral" or "multilateral"."

And in the organisations schema:
`recipient-country-budget` - "This element represents the budget for disbursements to a specific country across all projects."

Should these also be changed?

**Comment by stevieflow** [comment]
Yes, I think so

Re: `contact-info` needs checking:

> Contact information for the act. Specify whatever is available. You may repeat this element for each contact person.

**Comment by caprenter** [comment]
Moved to After 1.04 milestone as we need clarification on the issues raised by @Bjwebb above.

**Comment by Bjwebb** [comment]
Moving this into 2.01, as I think it should be considered in light of the description changes we have already made for 2.01.

`contact-info`, `activity-status`, `budget` and `recipient-country-budget` have been updated to say "activity" instead of "project", but `collaboration-type` has not.

Should the description of `collaboration-type` also be altered?

**Comment by bill-anderson** [comment]
Yes. The schema should always refer to activity. General guidance should explain what we mean by activity
