### ISSUE TITLE
location/@ref deprecated ?

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Schemas#89]
location/@ref is listed as deprecated:
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/
https://github.com/IATI/IATI-Schemas/blob/e99f96f1eb458884bc4b292b7e8caaa9fcb73a95/iati-activities-schema.xsd#L1184

However, this appears to be new in 1.04, and neither [the forum post](http://support.iatistandard.org/entries/30851856-Changes-to-Location-Element) or [Bill's summary table](https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdFJiX2FFS2VnVHc4ZkFFV2JObEV3Z2c#gid=1) list it as deprecated.

**Comment by caprenter** [comment]
Looks like a bug - the trail you point to would show this to be the case. 

Fixing will just be a case of removing the 'Deprecated in 1.04' text.
