### ISSUE TITLE
Convert percentages from integer to decimal

### ISSUE THREAD

**Issue by davidmegginson** [IATI/IATI-Schemas#9]
Details: http://wiki.iatistandard.org/standard/revision/1.03/changes_specification?&#allow_percentages_to_be_specified_as_decimals

**Comment by davidmegginson** [comment]
David: I'd like a second pair of eyes for each change.  I found four instances of the @percentage attribute in iati-activities.xsd (recipient-country, recipient-region, location, and second) and changed each of them from xsd:positiveInteger to xsd:decimal.

My changes are in the pre-version1.03 branch.  Could you check that out and verify, then close this issue?

The test tests/activity-tests/should-pass/26-decimal-percentage.xml verifies the change.

**Comment by caprenter** [comment]
I think that is correct.
