### ISSUE TITLE
result - schema text

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#91]
result:

> A measurable result of aid work.

We might want to expand/edit this?

**Comment by Bjwebb** [comment]
Bill's proposed this be changed in 2.01 https://github.com/IATI/IATI-Schemas/blob/7b973e9b310b858e842a948bef7c89cd60e55e29/iati-activities-schema.xsd#L1677 to:

> ```
>     A container for reporting outputs, outcomes, impacts and other
>     results that stem directly from the activity. This may be
>     repeated for each type of result reported.
> ```

@stevieflow does that resolve this issue?

**Comment by stevieflow** [comment]
Great, thanks.  I take it we will keep 1.0x as :

> A measurable result of aid work.

**Comment by Bjwebb** [comment]
Yes
