### ISSUE TITLE
activity-website - different languages

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#92]
The `activity-website` description states:

> A direct link to a web site or web page providing more information about the specific aid activity. Multiple links can be included. Multiple versions of the link may appear for different languages. Should not be general websites or addresses, and should include the http or https prefix.

However, there is no `xml:lang` or `language` attribute, etc - so it is unclear as to how to declare a website for an activity in multiple languages (which is a legitimate use case)

**Comment by Bjwebb** [comment]
@bill-anderson Does this need changing?

**Comment by bill-anderson** [comment]
Yes

**Comment by stevieflow** [comment]
@bill-anderson what does `activity-website` do/bring over and a `document-link` that is of format text/html (and can also have a category)?

**Comment by Bjwebb** [comment]
As part of 2.01 we're planning on redefining activity websites using document-link https://github.com/IATI/IATI-Schemas/issues/118
