### ISSUE TITLE
Implement 2.01: "6. Improvements to Organisation Standard"

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Schemas#95]
http://support.iatistandard.org/entries/57427467-Version-2-01-Iteration-1-6-Improvements-to-the-Organisation-Standard

In order for organisation-level documents to be classified by country it is proposed to:
- Create a document-link/recipient-country element
- To inherit properties from iati-activity/recipient-country

NB. New element `<budget-line>`
- For use as a sub-element in reporting budget breakdowns within
  - total-budget
  - recipient-org-budget
  - recipient-country-budget
- Create budget-line/@ref as a reporting organisation reference for the budget line
- Create budget-line/text for a description of the budget line (repeated for multiple languages)
- Create budget-line/value inherited from the existing valuesense element
- Usage
  - budget-line can be used in addition to OR instead of total-budget/value, recipient-org-budget/value and/or recipient-country-budget/value

Does this make high-level sense?

**Comment by Bjwebb** [comment]
Updated proposal link for Iteration 2: http://support.iatistandard.org/entries/76652763-Version-2-01-Iteration-2-6-Improvements-to-the-Organisation-Standard

I've created 3 separate GitHub issues to track the implementation of the two parts of this proposal:
- [Adding recipient-country to document-link](https://github.com/IATI/IATI-Schemas/issues/124)
- [Creating budget line element](https://github.com/IATI/IATI-Schemas/issues/123)
- [Replace iati-identifier with organisation-identifier](https://github.com/IATI/IATI-Schemas/issues/125)
