### ISSUE TITLE
location - administrative - level

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Schemas#96]
http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/administrative/

> An integer indicating the hierarchical level being reported. Level 0 is the national boundary, level 1 is the first-level administrative sub-division, etc.

The "etc" doesn't seem quite right/precise....

@bill-anderson

**Comment by bill-anderson** [comment]
... Level 2 is the second-level administrative subdivision, level n is the nth-level...

Or

One man went to mow, etc

Sent from my iPhone

On 24 Apr 2014, at 16:40, "Steven Flower" <notifications@github.com<mailto:notifications@github.com>> wrote:

http://dev.iatistandard.org/activities-standard/iati-activities/iati-activity/location/administrative/

An integer indicating the hierarchical level being reported. Level 0 is the national boundary, level 1 is the first-level administrative sub-division, etc.

The "etc" doesn't seem quite right/precise....

@bill-andersonhttps://github.com/bill-anderson

—
Reply to this email directly or view it on GitHubhttps://github.com/IATI/IATI-Schemas/issues/96.

---

This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com

---

---

This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com

---

**Comment by caprenter** [comment]
Perhaps we could illustrate this with a better example:
http://iatistandard.org/activity-standard/iati-activities/iati-activity/location/administrative/

**Comment by stevieflow** [comment]
If the example is not right/relevant we can edit the Example XML and Extra Docs - 

https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/activity-standard/activity-standard-example-1.04-annotated.xml

https://github.com/IATI/IATI-Extra-Documentation/blob/version-1.04/en/activity-standard/iati-activities/iati-activity/location/administrative.rst

I would advocate doing the two together though - rather than create more isolated/bespoke examples

Further - if we think different types of `location` examples are needed (and not always using all the sub elements) then this is perfectly achievable through creating new examples in the Example XML and adding appropriate comments through which to pull it in

**Comment by akmiller01** [comment]
Looks like this phrasing no longer applies:
```
A number defining a subdivision within a hierarchical system of administrative areas. The precise system for defining the particular meaning of each @level value is determined by the @vocabulary being used.
```
